'CPU-only read-only web dashboard for the frozen WF-3 depth product. The dashboard is deliberately a product reader, not a solver adapter. It will serve an empty state until a producer has written a contract-valid segment product and its source manifest. No depth, status, geometry, or summary value is generated by this module. The HTTP surface is intentionally small: * ``/`` serves the static dashboard; * ``/api/state`` exposes the available immutable product snapshots; * ``/api/segments`` exposes one selected snapshot as GeoJSON; * ``/api/context/<name>`` serves allowlisted WF-6 context assets from ``data/interim/context/`` (wards blobs + meta sidecars, the segment->ward join, the search index, the forcing series); * ``/api/watchlist`` and ``/api/intersections`` run the WF-6 lane builders against the store\'s active realized product (frame param: tag|index|"held"); * ``/api/drains/causal?segment_id=`` maps one street segment onto nearby predicted-overcapacity drain edges via an injected midpoint provider over the realized centreline GeoPackage. * ``/api/comparison2022`` streams the realized WF8 sim-vs-sim agreement (runs/wf8_sim_vs_sim_3h_vs_replay/comparison.json) — every number in the strip is read from this file, never hardcoded (rule 3). Honest 404 {"error":"comparison product missing"} when the artifact is absent. Load-once cache, verbatim bytes. * ``/api/comparison2022/observed.json`` is retired: returns 404 {"error":"retired: SAR observed view replaced by sim-vs-sim agreement"}. Response shapes --------------- ``/api/comparison2022``: the WF8 comparison.json object verbatim (keys: kind, banned_note, left, right, offset, counts, metrics, band_cross_tab, provenance) — a cross-model consistency statement, neither panel is an observation; the word accuracy is deliberately absent. ``/api/comparison2022/observed.json``: retired — 404 {"error":"retired: SAR observed view replaced by sim-vs-sim agreement"}. Run the module with ``python -m jaladhar.web.app serve``. ``check`` is a CPU-only smoke check that does not create or mutate a run.'  # noqa: E501

from __future__ import annotations

import csv
import json
import mimetypes
import os
import re
import subprocess
import tempfile
import threading
import time
import uuid
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, cast
from urllib.parse import parse_qs, unquote, urlsplit

import typer

from jaladhar.validation.depth_product_contract import (
    MAX_FORECAST_LEAD_MINUTES,
    DepthProductContractError,
    DepthProductRequirements,
    load_requirements,
    sha256_file,
    validate_product_manifest,
)
from jaladhar.web.basemap import BUNDLE, BasemapError, gzip_if_accepted
from jaladhar.web.drains import READER as DRAIN_READER
from jaladhar.web.intersections import build_intersections
from jaladhar.web.series import FrameSeries, detect_series
from jaladhar.web.watchlist import build_watchlist, resolve_product_source

REPO_ROOT = Path(__file__).resolve().parents[3]
STATIC_ROOT = Path(__file__).resolve().parent / "static"
PRODUCT_FILE_RE = re.compile(r"segment_status(?:[_-].*)?\.(?:csv|json)$", re.IGNORECASE)
CONTRACT_GAPS = (
    "Road geometry is a separate realized artifact; the browser renders only a bounded preview "
    "and never claims full-city browser coverage.",
    "The frozen depth-product contract defines one product file per expected segment set, "
    "but does not define a multi-lead collection. The slider therefore exposes only lead "
    "values realized by supplied product files.",
    "Scientific gate status is read from a separately hash-bound report; product bytes loaded "
    "does not mean gate acceptance.",
)
MAX_GEOMETRY_PREVIEW_FEATURES = 2_000
SELECTION_ORDER = "frame_series_over_flat_event_maximum__newest_valid_first"

# event-maximum score with an explicit scope suffix, never a bare status that
EVENT_MAXIMUM_AGGREGATION = "event_maximum"
EVENT_MAXIMUM_SCOPE = "event_maximum"
EVENT_MAXIMUM_SUFFIX = " · event maximum"


def _event_maximum_label(raw: Any) -> Any:
    "Append the explicit event-maximum scope marker to a G1 display string. Non-string statuses pass through untouched so absent fields stay absent."  # noqa: E501
    if isinstance(raw, str) and raw:
        return f"{raw}{EVENT_MAXIMUM_SUFFIX}"
    return raw


CONTEXT_DIR = REPO_ROOT / "data" / "interim" / "context"
CONTEXT_ASSET_ALT_PATHS: dict[str, Path] = {
    "vehicle_wading_policy.json": REPO_ROOT / "data" / "curation" / "vehicle_wading_policy.json",
}
CONTEXT_ASSET_TYPES: dict[str, str] = {
    "wards_2022.bin": "application/octet-stream",
    "wards_2022.meta.json": "application/json",
    "wards_2023.bin": "application/octet-stream",
    "wards_2023.meta.json": "application/json",
    "segment_ward_2022.csv.gz": "application/gzip",
    "search_index.json": "application/json",
    "forcing_series.json": "application/json",
    "vehicle_wading_policy.json": "application/json",
}

ROAD_CENTRELINES_PATH = REPO_ROOT / "data" / "interim" / "terrain" / "roads_centrelines.gpkg"

_WARD_MEMBERSHIP_LOCK = threading.Lock()
_WARD_MEMBERSHIP: dict[str, Any] | None = None


def _ward_membership() -> dict[str, Any]:
    global _WARD_MEMBERSHIP
    import gzip

    import numpy as np

    with _WARD_MEMBERSHIP_LOCK:
        if _WARD_MEMBERSHIP is not None:
            return _WARD_MEMBERSHIP
        path = CONTEXT_DIR / "segment_ward_2022.csv.gz"
        if not path.is_file():
            raise DashboardError(f"ward membership artifact missing: {path}")
        ward_names: list[str] = []
        name_to_no: dict[str, int] = {}
        street_by_segment: dict[int, str] = {}
        ward_of_segment = np.zeros(176172, dtype="<u4")
        with gzip.open(path, "rt", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                try:
                    seg = int(row["segment_id"])
                    ward_no = int(row["ward_no"])
                except (TypeError, ValueError, KeyError) as exc:
                    raise DashboardError(f"ward membership row unreadable: {exc}") from exc
                ward_name = (row.get("ward_name") or "").strip()
                if ward_name and ward_name not in name_to_no:
                    name_to_no[ward_name] = ward_no
                    ward_names.append(ward_name)
                if 1 <= seg <= 176171:
                    ward_of_segment[seg] = ward_no
                    street = (row.get("street_name") or "").strip()
                    if street:
                        street_by_segment[seg] = street
        _WARD_MEMBERSHIP = {
            "path": path,
            "ward_names": ward_names,
            "name_to_no": name_to_no,
            "street_by_segment": street_by_segment,
            "ward_of_segment": ward_of_segment,
        }
        return _WARD_MEMBERSHIP


COMPARISON_JSON_PATH = REPO_ROOT / "runs" / "wf8_sim_vs_sim_3h_vs_replay" / "comparison.json"
_COMPARISON_LOCK = threading.Lock()
_COMPARISON_CACHE: bytes | None = None
_COMPARISON_CACHE_ERROR: str | None = None

REPLAY_SERIES_DIR = REPO_ROOT / "runs" / "wf3_replay2_uncoupled_baseline_frames_v2"
_REPLAY_FRAME_TAG_RE = re.compile(r"^t\d{6,8}$")
_REPLAY_SERIES_LOCK = threading.Lock()
_REPLAY_SERIES: FrameSeries | None = None


def _replay_series() -> FrameSeries:
    global _REPLAY_SERIES
    with _REPLAY_SERIES_LOCK:
        if _REPLAY_SERIES is None:
            if not (REPLAY_SERIES_DIR / "manifest.json").is_file():
                raise DashboardError(f"replay frame series manifest missing: {REPLAY_SERIES_DIR}")
            _REPLAY_SERIES = FrameSeries(REPLAY_SERIES_DIR, repo_root=REPO_ROOT)
        return _REPLAY_SERIES


LIVE_TILE = "1200,2055,1200,2078"
LIVE_TILE_TUPLE = (1200, 2055, 1200, 2078)
LIVE_COOLDOWN_S = 120
LIVE_JOBS: dict[str, dict[str, Any]] = {}
LIVE_JOBS_LOCK = threading.Lock()
LIVE_SINGLE_FLIGHT = threading.Semaphore(1)
LIVE_LAST_START: dict[str, Any] = {"ts": None, "iso": None}


def _live_manifest_authoritative(job: dict[str, Any]) -> dict[str, Any]:
    enriched = dict(job)
    out_dir_str = job.get("out_dir")
    if not out_dir_str:
        return enriched
    try:
        manifest_path = (
            REPO_ROOT / job.get("manifest_path", "")
            if job.get("manifest_path")
            else REPO_ROOT / out_dir_str / "manifest.json"
        )
        if not manifest_path.is_file():
            alt = REPO_ROOT / out_dir_str / "manifest.json"
            if alt.is_file():
                manifest_path = alt
        if manifest_path.is_file():
            payload = json.loads(manifest_path.read_text(encoding="utf-8"))
            if isinstance(payload, dict):
                enriched["manifest_status"] = payload.get("status")
                enriched["manifest_path"] = payload.get("manifest_path") or str(
                    manifest_path.relative_to(REPO_ROOT)
                )
                m_status = payload.get("status")
                if m_status == "completed" and enriched.get("status") in ("queued", "running"):
                    enriched["status"] = "completed"
                    if not enriched.get("finished_utc"):
                        enriched["finished_utc"] = payload.get("end_time_iso")
                elif m_status == "failed" and enriched.get("status") in ("queued", "running"):
                    enriched["status"] = "failed"
                latency = payload.get("latency_g4") or {}
                if isinstance(latency, dict):
                    enriched["wall_clock_s"] = latency.get("wall_clock_sec")
                    enriched["wall_clock_min"] = latency.get("wall_clock_min")
                    enriched["steps"] = latency.get("steps")
                    enriched["g4_passes"] = latency.get("g4_passes")
                    enriched["latency"] = latency
                enriched["tile"] = payload.get("tile") or {
                    "canonical_coords": list(LIVE_TILE_TUPLE)
                }
                enriched["valid_time_utc"] = payload.get("window", {}).get("end") or payload.get(
                    "forecast_experiment", {}
                ).get("valid_utc")
                enriched["completed_utc"] = payload.get("end_time_iso")
                if "gpu_realized" in payload:
                    enriched["gpu_realized"] = payload.get("gpu_realized")
                try:
                    out_abs = REPO_ROOT / out_dir_str
                    if out_abs.is_dir():
                        enriched["out_dir_exists"] = True
                        enriched["out_dir_listing_hint"] = sorted(
                            [p.name for p in out_abs.iterdir()][:12]
                        )
                except Exception:
                    pass
    except Exception:
        pass
    return enriched


class RoadMidpoints:

    def __init__(self, path: Path) -> None:
        self.path = path
        self.lock = threading.Lock()
        self._points: dict[int, list[float]] | None = None
        self._error: str | None = None

    @property
    def available(self) -> bool:
        return self.path.is_file() and self._error is None

    def _load(self) -> None:
        if self._points is not None or self._error is not None:
            return
        if not self.path.is_file():
            self._error = f"centreline artifact missing: {self.path}"
            return
        try:
            import fiona

            points: dict[int, list[float]] = {}
            with fiona.open(self.path) as source:
                for feature in source:
                    properties = feature.get("properties") or {}
                    try:
                        segment_id = int(properties.get("segment_id"))
                    except (TypeError, ValueError):
                        continue
                    if segment_id in points:
                        continue
                    first = _geometry_first_vertex(feature.get("geometry"))
                    last = _geometry_last_vertex(feature.get("geometry"))
                    if first is None or last is None:
                        continue
                    points[segment_id] = [
                        (first[0] + last[0]) / 2.0,
                        (first[1] + last[1]) / 2.0,
                    ]
            if not points:
                raise DashboardError(f"centreline artifact yielded no midpoints: {self.path}")
            self._points = points
        except Exception as exc:  # noqa: BLE001 - degrade honestly, never guess
            self._error = f"{type(exc).__name__}: {exc}"

    def provide(self, segment_id: str | int) -> list[float] | None:
        with self.lock:
            self._load()
            points = self._points
        if points is None:
            return None
        try:
            point = points[int(segment_id)]
        except (TypeError, ValueError, KeyError):
            return None
        return [point[0], point[1]]


def _geometry_coordinates(geometry: Any) -> Any:
    if geometry is None:
        return None
    get = getattr(geometry, "get", None)
    if get is not None:
        try:
            return get("coordinates")
        except Exception:  # noqa: BLE001 - fall through to attribute access
            pass
    return getattr(geometry, "coordinates", None)


def _geometry_first_vertex(geometry: Any) -> tuple[float, float] | None:
    coords = _geometry_coordinates(geometry)
    while isinstance(coords, (list, tuple)) and coords and isinstance(coords[0], (list, tuple)):
        coords = coords[0]
    if (
        isinstance(coords, (list, tuple))
        and len(coords) >= 2
        and all(isinstance(v, (int, float)) for v in coords[:2])
    ):
        return (float(coords[0]), float(coords[1]))
    return None


def _geometry_last_vertex(geometry: Any) -> tuple[float, float] | None:
    coords = _geometry_coordinates(geometry)
    while isinstance(coords, (list, tuple)) and coords and isinstance(coords[-1], (list, tuple)):
        coords = coords[-1]
    if (
        isinstance(coords, (list, tuple))
        and len(coords) >= 2
        and all(isinstance(v, (int, float)) for v in coords[:2])
    ):
        return (float(coords[0]), float(coords[1]))
    return None


CAUSAL_MIDPOINTS = RoadMidpoints(ROAD_CENTRELINES_PATH)

_LANES_CACHE_LOCK = threading.Lock()
_LANES_CACHE: dict[tuple[str, str, str], dict[str, Any]] = {}


def _active_product_source(store: DashboardStore) -> Any:
    if store.series is not None and store.series.ready:
        return resolve_product_source(store.series.run_dir, repo_root=store.repo_root)
    if store.snapshots:
        products_dir = store.snapshots[-1].path.parent
        return resolve_product_source(products_dir, repo_root=store.repo_root)
    raise DashboardError("no realized depth product is loaded; watchlist/intersections refused")


def _resolve_lane_frame(source: Any, frame_param: str) -> tuple[Any, str]:
    raw = (frame_param or "").strip() or "held"
    if raw.lower() == "held":
        if getattr(source, "kind", "") == "frame" and source.frames:
            return len(source.frames) - 1, f"held:{source.frames[-1].tag}"
        return None, "flat"
    return raw, f"given:{raw}"


def _lane_payload(store: DashboardStore, kind: str, frame_param: str) -> dict[str, Any]:
    source = _active_product_source(store)
    frame_value, frame_key = _resolve_lane_frame(source, frame_param)
    cache_key = (kind, str(source.run_id), frame_key)
    with _LANES_CACHE_LOCK:
        cached = _LANES_CACHE.get(cache_key)
    if cached is not None:
        return cached
    if kind == "watchlist":
        payload = build_watchlist(source, frame_value, repo_root=store.repo_root)
    else:
        payload = build_intersections(source, frame_value, repo_root=store.repo_root)
    with _LANES_CACHE_LOCK:
        _LANES_CACHE[cache_key] = payload
    return payload


def _serve_comparison(handler: BaseHTTPRequestHandler) -> None:
    global _COMPARISON_CACHE, _COMPARISON_CACHE_ERROR
    with _COMPARISON_LOCK:
        if _COMPARISON_CACHE is not None:
            body = _COMPARISON_CACHE
            handler.send_response(HTTPStatus.OK)
            handler.send_header("Content-Type", "application/json; charset=utf-8")
            handler.send_header("Content-Length", str(len(body)))
            handler.send_header("Cache-Control", "no-store")
            handler.end_headers()
            handler.wfile.write(body)
            return
        if _COMPARISON_CACHE_ERROR is not None:
            _json_response(handler, HTTPStatus.NOT_FOUND, {"error": "comparison product missing"})
            return
        path = COMPARISON_JSON_PATH
        if not path.is_file():
            _COMPARISON_CACHE_ERROR = "missing"
            _json_response(handler, HTTPStatus.NOT_FOUND, {"error": "comparison product missing"})
            return
        try:
            body = path.read_bytes()
            json.loads(body.decode("utf-8"))
            _COMPARISON_CACHE = body
        except Exception as exc:  # noqa: BLE001
            _COMPARISON_CACHE_ERROR = f"{type(exc).__name__}: {exc}"
            _json_response(
                handler,
                HTTPStatus.INTERNAL_SERVER_ERROR,
                {"error": f"comparison artifact unreadable: {exc}"},
            )
            return
        handler.send_response(HTTPStatus.OK)
        handler.send_header("Content-Type", "application/json; charset=utf-8")
        handler.send_header("Content-Length", str(len(body)))
        handler.send_header("Cache-Control", "no-store")
        handler.end_headers()
        handler.wfile.write(body)


def _serve_comparison_observed(handler: BaseHTTPRequestHandler) -> None:
    _json_response(
        handler,
        HTTPStatus.NOT_FOUND,
        {"error": "retired: SAR observed view replaced by sim-vs-sim agreement"},
    )


app = typer.Typer(add_completion=False, no_args_is_help=True)


class ContractViolation(ValueError):
    pass


class DashboardError(RuntimeError):
    pass


def _repo_relative(path: Path, repo_root: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError:
        return str(path.resolve())


def _safe_repo_path(path: Path, repo_root: Path, *, label: str) -> Path:
    resolved = path.expanduser().resolve()
    try:
        resolved.relative_to(repo_root.resolve())
    except ValueError as exc:
        raise DashboardError(f"{label} must be inside the repository: {path}") from exc
    return resolved


def _parse_int(value: Any, *, field: str, row_number: int | None = None) -> int:
    location = f" at row {row_number}" if row_number is not None else ""
    if isinstance(value, bool):
        raise ContractViolation(f"{field}{location} must be an integer, not a boolean")
    if isinstance(value, int):
        return value
    if isinstance(value, str) and re.fullmatch(r"[+-]?\d+", value.strip()):
        return int(value.strip())
    raise ContractViolation(f"{field}{location} must be an integer")


def _parse_timestamp(value: Any, *, field: str, row_number: int) -> datetime:
    if not isinstance(value, str) or not value.strip():
        raise ContractViolation(f"{field} at row {row_number} must be an ISO8601 UTC timestamp")
    text = value.strip()
    if text.endswith("Z"):
        text = f"{text[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError as exc:
        raise ContractViolation(f"{field} at row {row_number} is not ISO8601: {value!r}") from exc
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise ContractViolation(f"{field} at row {row_number} must be timezone-aware UTC")
    if parsed.utcoffset() != UTC.utcoffset(parsed):
        raise ContractViolation(f"{field} at row {row_number} must carry a UTC offset")
    return parsed.astimezone(UTC)


def _load_json(path: Path, *, label: str) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ContractViolation(f"could not read {label} {path}: {exc}") from exc


def _contract(repo_root: Path) -> dict[str, Any]:
    path = repo_root / "configs" / "contracts" / "depth_product.json"
    payload = _load_json(path, label="frozen depth-product contract")
    if not isinstance(payload, dict):
        raise DashboardError(f"frozen depth-product contract is not an object: {path}")
    return cast(dict[str, Any], payload)


def _extract_product_rows(payload: Any, *, path: Path) -> list[dict[str, Any]]:

    if isinstance(payload, list):
        raw_rows = payload
    elif isinstance(payload, dict) and isinstance(payload.get("features"), list):
        raw_rows = []
        for feature in payload["features"]:
            if not isinstance(feature, dict) or not isinstance(feature.get("properties"), dict):
                raise ContractViolation(f"JSON product feature has no properties object: {path}")
            row = dict(feature["properties"])
            if feature.get("geometry") is not None:
                row["_geometry"] = feature["geometry"]
            raw_rows.append(row)
    elif isinstance(payload, dict) and isinstance(payload.get("rows"), list):
        raw_rows = payload["rows"]
    elif isinstance(payload, dict) and isinstance(payload.get("segments"), list):
        raw_rows = payload["segments"]
    else:
        raise ContractViolation(
            f"JSON product {path} must be a row array, rows/segments envelope, or "
            "GeoJSON FeatureCollection"
        )

    rows: list[dict[str, Any]] = []
    for number, raw in enumerate(raw_rows, start=2):
        if not isinstance(raw, dict):
            raise ContractViolation(f"JSON product row {number} is not an object: {path}")
        rows.append(dict(raw))
    return rows


def _read_product_rows(path: Path) -> list[dict[str, Any]]:
    suffix = path.suffix.lower()
    if suffix == ".json":
        return _extract_product_rows(_load_json(path, label="depth product"), path=path)
    if suffix != ".csv":
        raise ContractViolation(f"unsupported depth-product format: {path.suffix}")
    try:
        with path.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            if reader.fieldnames is None:
                raise ContractViolation(f"CSV depth product has no header: {path}")
            rows = [dict(row) for row in reader]
    except OSError as exc:
        raise ContractViolation(f"could not read CSV depth product {path}: {exc}") from exc
    return rows


def _lookup_ids(repo_root: Path) -> set[int]:
    path = repo_root / "data" / "interim" / "terrain" / "roads_segment_lookup.csv"
    if not path.is_file():
        raise ContractViolation(
            f"required segment lookup is missing: {_repo_relative(path, repo_root)}"
        )
    try:
        with path.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            if reader.fieldnames is None or "segment_id" not in reader.fieldnames:
                raise ContractViolation(f"segment lookup has no segment_id column: {path}")
            ids: set[int] = set()
            for number, row in enumerate(reader, start=2):
                ids.add(
                    _parse_int(row.get("segment_id"), field="lookup.segment_id", row_number=number)
                )
    except OSError as exc:
        raise ContractViolation(f"could not read segment lookup {path}: {exc}") from exc
    if not ids:
        raise ContractViolation(f"segment lookup contains no realized ids: {path}")
    return ids


def _manifest_path(repo_root: Path, source_manifest: Any) -> Path:
    if not isinstance(source_manifest, str) or not source_manifest.strip():
        raise ContractViolation("source_manifest_path must be a non-empty repository-relative path")
    raw = Path(source_manifest)
    if raw.is_absolute() or ".." in raw.parts:
        raise ContractViolation("source_manifest_path must remain repository-relative")
    path = repo_root / raw
    try:
        path.resolve().relative_to(repo_root.resolve())
    except ValueError as exc:
        raise ContractViolation("source_manifest_path escapes the repository") from exc
    if not path.is_file():
        raise ContractViolation(f"source manifest does not exist: {source_manifest}")
    return path.resolve()


def _manifest_required(manifest: dict[str, Any], key: str, *, path: Path, repo_root: Path) -> Any:
    if key not in manifest:
        raise ContractViolation(
            f"source manifest {_repo_relative(path, repo_root)} lacks required field {key!r}"
        )
    return manifest[key]


def _validate_manifest(
    manifest: dict[str, Any],
    manifest_path: Path,
    *,
    repo_root: Path,
    run_id: str,
    rows: Sequence[dict[str, Any]],
    lookup_ids: set[int],
    contract_path: Path,
) -> dict[str, Any]:
    try:
        return validate_product_manifest(
            manifest,
            manifest_path,
            rows=rows,
            lookup_ids=lookup_ids,
            repo_root=repo_root,
            contract_path=contract_path,
        )
    except DepthProductContractError as exc:
        raise ContractViolation(str(exc)) from exc


def _normalize_row(
    row: dict[str, Any],
    *,
    number: int,
    repo_root: Path,
    requirements: DepthProductRequirements,
) -> dict[str, Any]:
    required = {
        "run_id",
        "segment_id",
        "band_low_cm",
        "band_high_cm",
        "confidence",
        "flood_status",
        "valid_time_utc",
        "issue_time_utc",
        "forecast_lead_minutes",
        "source_manifest_path",
    }
    missing = sorted(key for key in required if key not in row or row[key] in (None, ""))
    if missing:
        raise ContractViolation(f"depth product row {number} missing fields: {', '.join(missing)}")

    segment_id = _parse_int(row["segment_id"], field="segment_id", row_number=number)
    band_low = _parse_int(row["band_low_cm"], field="band_low_cm", row_number=number)
    band_high = _parse_int(row["band_high_cm"], field="band_high_cm", row_number=number)
    lead = _parse_int(
        row["forecast_lead_minutes"], field="forecast_lead_minutes", row_number=number
    )
    if segment_id < 1:
        raise ContractViolation(f"segment_id at row {number} must be positive")
    if band_low < 0 or band_high < 0 or band_low > band_high:
        raise ContractViolation(
            f"depth band at row {number} is not an ordered non-negative cm band"
        )
    if not 0 <= lead <= MAX_FORECAST_LEAD_MINUTES:
        raise ContractViolation(f"forecast_lead_minutes at row {number} must be within 0-180")

    confidence = str(row["confidence"])
    flood_status = str(row["flood_status"])
    if confidence not in {"modeled_direct", "modeled_interpolated", "no_data"}:
        raise ContractViolation(f"confidence at row {number} is not a frozen enum value")
    if confidence == "modeled_interpolated":
        raise ContractViolation(
            f"modeled_interpolated at row {number} is reserved and cannot be produced in v1"
        )
    if flood_status not in {"flooded", "not_flooded", "unknown"}:
        raise ContractViolation(f"flood_status at row {number} is not a frozen enum value")

    if confidence == "no_data":
        if flood_status != "unknown" or (band_low, band_high) != (0, 0):
            raise ContractViolation(
                f"no_data row {number} must be unknown with band [0, 0], got "
                f"{flood_status!r} [{band_low}, {band_high}]"
            )
    elif flood_status == "unknown":
        raise ContractViolation(f"modeled row {number} cannot have flood_status=unknown")
    if flood_status == "flooded" and band_high < requirements.flood_threshold_cm:
        raise ContractViolation(
            f"flooded row {number} has band_high_cm below the frozen flood rule"
        )

    valid_time = _parse_timestamp(row["valid_time_utc"], field="valid_time_utc", row_number=number)
    issue_time = _parse_timestamp(row["issue_time_utc"], field="issue_time_utc", row_number=number)
    if lead == 0 and issue_time < valid_time:
        raise ContractViolation(f"nowcast row {number} has issue_time_utc before valid_time_utc")
    if lead > 0 and issue_time > valid_time:
        raise ContractViolation(f"forecast row {number} has issue_time_utc after valid_time_utc")

    run_id = row["run_id"]
    if not isinstance(run_id, str) or not run_id.strip():
        raise ContractViolation(f"run_id at row {number} must be a non-empty string")
    source_manifest = row["source_manifest_path"]
    _manifest_path(repo_root, source_manifest)

    normalized = dict(row)
    normalized.update(
        {
            "run_id": run_id,
            "segment_id": segment_id,
            "band_low_cm": band_low,
            "band_high_cm": band_high,
            "confidence": confidence,
            "flood_status": flood_status,
            "valid_time_utc": valid_time.isoformat().replace("+00:00", "Z"),
            "issue_time_utc": issue_time.isoformat().replace("+00:00", "Z"),
            "forecast_lead_minutes": lead,
            "source_manifest_path": str(source_manifest),
        }
    )
    return normalized


@dataclass(frozen=True)
class Snapshot:

    path: Path
    run_id: str
    lead_minutes: int
    rows: tuple[dict[str, Any], ...]
    manifest_path: Path
    manifest: dict[str, Any]
    manifest_view: dict[str, Any]


def _load_snapshot(
    path: Path,
    *,
    repo_root: Path,
    lookup_ids: set[int],
    contract_path: Path,
    requirements: DepthProductRequirements,
) -> Snapshot:
    raw_rows = _read_product_rows(path)
    if not raw_rows:
        raise ContractViolation(f"depth product is empty: {_repo_relative(path, repo_root)}")
    rows = tuple(
        _normalize_row(
            row,
            number=number,
            repo_root=repo_root,
            requirements=requirements,
        )
        for number, row in enumerate(raw_rows, start=2)
    )
    run_ids = {row["run_id"] for row in rows}
    if len(run_ids) != 1:
        raise ContractViolation("depth product contains more than one run_id")
    source_paths = {row["source_manifest_path"] for row in rows}
    if len(source_paths) != 1:
        raise ContractViolation("depth product contains more than one source_manifest_path")
    leads = {row["forecast_lead_minutes"] for row in rows}
    if len(leads) != 1:
        raise ContractViolation(
            "one product file contains more than one forecast lead; the frozen contract "
            "requires one row per expected segment set, so supply separate immutable files "
            "for the slider"
        )
    valid_times = {row["valid_time_utc"] for row in rows}
    issue_times = {row["issue_time_utc"] for row in rows}
    if len(valid_times) != 1 or len(issue_times) != 1:
        raise ContractViolation(
            "depth product snapshot metadata changes valid_time_utc or issue_time_utc "
            "within one product file"
        )
    ids = [row["segment_id"] for row in rows]
    if len(set(ids)) != len(ids):
        raise ContractViolation("depth product contains duplicate segment_id values")
    product_ids = set(ids)
    if product_ids != lookup_ids:
        missing = len(lookup_ids - product_ids)
        unexpected = len(product_ids - lookup_ids)
        raise ContractViolation(
            "product segment_id set disagrees with realized lookup "
            f"(missing={missing}, unexpected={unexpected})"
        )

    run_id = next(iter(run_ids))
    manifest_path = _manifest_path(repo_root, next(iter(source_paths)))
    manifest_payload = _load_json(manifest_path, label="source manifest")
    if not isinstance(manifest_payload, dict):
        raise ContractViolation(f"source manifest is not an object: {manifest_path}")
    manifest = cast(dict[str, Any], manifest_payload)
    manifest_view = _validate_manifest(
        manifest,
        manifest_path,
        repo_root=repo_root,
        run_id=run_id,
        rows=rows,
        lookup_ids=lookup_ids,
        contract_path=contract_path,
    )
    return Snapshot(
        path=path,
        run_id=run_id,
        lead_minutes=next(iter(leads)),
        rows=rows,
        manifest_path=manifest_path,
        manifest=manifest,
        manifest_view=manifest_view,
    )


def _candidate_products(repo_root: Path, product: Path | None) -> list[Path]:
    if product is not None:
        resolved = _safe_repo_path(product, repo_root, label="product")
        if not resolved.exists():
            return []
        if resolved.is_dir():
            return sorted(
                path
                for path in resolved.iterdir()
                if path.is_file() and PRODUCT_FILE_RE.fullmatch(path.name)
            )
        if resolved.is_file() and PRODUCT_FILE_RE.fullmatch(resolved.name):
            stem = resolved.with_suffix("")
            return sorted(
                path
                for path in (stem.with_suffix(".csv"), stem.with_suffix(".json"))
                if path.is_file()
            )
        raise DashboardError(
            f"product must be a segment_status CSV/JSON or its products directory: {product}"
        )

    candidates = [
        path for path in repo_root.glob("runs/**/products/segment_status*.csv") if path.is_file()
    ]
    candidates.extend(
        path for path in repo_root.glob("runs/**/products/segment_status*.json") if path.is_file()
    )
    return sorted(set(candidates))


class GeometryIndex:

    def __init__(self, path: Path | None, *, repo_root: Path) -> None:
        self.path = path
        self.repo_root = repo_root
        self._features: dict[int, dict[str, Any]] | None = None
        self.crs: str | None = None
        self.error: str | None = None
        if path is not None:
            try:
                self.path = _safe_repo_path(path, repo_root, label="geometry")
                if not self.path.is_file():
                    raise DashboardError(f"geometry artifact does not exist: {path}")
            except (DashboardError, OSError) as exc:
                self.error = str(exc)

    @property
    def available(self) -> bool:
        return self.path is not None and self.error is None

    def _read(self) -> None:
        if self._features is not None or not self.available:
            return
        assert self.path is not None
        if self.path.suffix.lower() in {".json", ".geojson"}:
            payload = _load_json(self.path, label="geometry artifact")
            features = payload.get("features") if isinstance(payload, dict) else None
            if not isinstance(features, list):
                raise DashboardError(
                    f"geometry JSON is not a GeoJSON FeatureCollection: {self.path}"
                )
            result: dict[int, dict[str, Any]] = {}
            for feature in features:
                if not isinstance(feature, dict) or not isinstance(feature.get("properties"), dict):
                    continue
                raw_id = feature["properties"].get("segment_id", feature.get("id"))
                try:
                    segment_id = _parse_int(raw_id, field="geometry.segment_id")
                except ContractViolation:
                    continue
                if feature.get("geometry") is not None:
                    result[segment_id] = cast(dict[str, Any], feature["geometry"])
            self._features = result
            self.crs = "GeoJSON CRS (producer declaration not present in frozen product contract)"
            return

        try:
            import fiona
        except ImportError as exc:
            raise DashboardError(
                "fiona is required to read a GeoPackage geometry artifact"
            ) from exc
        try:
            layers = fiona.listlayers(self.path)
            if not layers:
                raise DashboardError(f"geometry GeoPackage has no layers: {self.path}")
            result = {}
            with fiona.open(self.path, layer=layers[0]) as source:
                self.crs = source.crs_wkt or str(source.crs) or None
                for feature in source:
                    properties = dict(feature.get("properties") or {})
                    raw_id = properties.get("segment_id", feature.get("id"))
                    try:
                        segment_id = _parse_int(raw_id, field="geometry.segment_id")
                    except ContractViolation:
                        continue
                    geometry = feature.get("geometry")
                    if geometry is not None:
                        result[segment_id] = dict(geometry)
        except (OSError, ValueError) as exc:
            raise DashboardError(f"could not read geometry artifact {self.path}: {exc}") from exc
        self._features = result

    def for_ids(self, ids: Iterable[int]) -> dict[int, dict[str, Any]]:
        self._read()
        if self._features is None:
            return {}
        return {
            segment_id: self._features[segment_id]
            for segment_id in ids
            if segment_id in self._features
        }


def _flat_probe_reason(twins: dict[str, Path], *, repo_root: Path) -> str | None:

    try:
        if set(twins) != {".csv", ".json"}:
            return "incomplete CSV/JSON twin pair"
        manifest_path = next(iter(twins.values())).parent.parent / "manifest.json"
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            return "run manifest is not an object"
        if payload.get("status") != "completed":
            return f"manifest status is {payload.get('status')!r}, not 'completed'"
        admission_relative = payload.get("uncoupled_baseline_admission_path")
        admission_sha = payload.get("uncoupled_baseline_admission_sha256")
        if isinstance(admission_relative, str) and isinstance(admission_sha, str):
            actual = sha256_file(repo_root / admission_relative)
            if actual != admission_sha:
                return (
                    "stale uncoupled_baseline_admission_sha256 "
                    f"{admission_sha[:12]}... vs realized admission bytes {actual[:12]}..."
                )
        return None
    except (ContractViolation, DashboardError, OSError, json.JSONDecodeError) as exc:
        return str(exc)


class DashboardStore:

    def __init__(
        self,
        *,
        repo_root: Path = REPO_ROOT,
        product: Path | None = None,
        geometry: Path | None = None,
        gate_report: Path | None = None,
    ) -> None:
        self.repo_root = repo_root.resolve()
        self.product_argument = product
        self.contract = _contract(self.repo_root)
        self.contract_path = self.repo_root / "configs" / "contracts" / "depth_product.json"
        self.requirements = load_requirements(self.contract_path)
        self.geometry = GeometryIndex(geometry, repo_root=self.repo_root)
        self.gate_report_argument = gate_report
        self.snapshots: tuple[Snapshot, ...] = ()
        self.error: str | None = None
        self.skipped_candidates: list[dict[str, str]] = []
        # distinct-lead rule correctly refuses for a replay time series.
        self.series = detect_series(product, repo_root=self.repo_root)
        if self.series is not None:
            if product is None:
                self._annotate_flat_candidates()
            return
        try:
            lookup_ids = _lookup_ids(self.repo_root)
            self.snapshots = self._load_snapshots_quarantined(lookup_ids)
            if not self.snapshots and self.skipped_candidates:
                raise ContractViolation(
                    "no candidate depth product validated: "
                    + "; ".join(
                        f"{entry['candidate']}: {entry['reason']}"
                        for entry in self.skipped_candidates
                    )
                )
        except (ContractViolation, DashboardError, OSError, json.JSONDecodeError) as exc:
            self.error = str(exc)

    def _record_skip(self, candidate: str, kind: str, disposition: str, reason: str) -> None:
        self.skipped_candidates.append(
            {
                "candidate": candidate,
                "kind": kind,
                "disposition": disposition,
                "reason": reason,
            }
        )
        if disposition == "skipped":
            typer.echo(f"dashboard: skipped candidate {candidate}: {reason}", err=True)

    def _manifest_recency(self, stem: Path) -> tuple[str, str]:

        manifest_path = stem.parent.parent / "manifest.json"
        try:
            payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return ("", "")
        if not isinstance(payload, dict):
            return ("", "")
        return (
            str(payload.get("end_time_iso") or payload.get("start_time_iso") or ""),
            "",
        )

    def _flat_probe_disposition(self, twins: dict[str, Path]) -> str | None:
        return _flat_probe_reason(twins, repo_root=self.repo_root)

    def _annotate_flat_candidates(self) -> None:
        candidates = _candidate_products(self.repo_root, None)
        grouped: dict[Path, dict[str, Path]] = {}
        for path in candidates:
            grouped.setdefault(path.with_suffix(""), {})[path.suffix.lower()] = path
        ordered = sorted(
            grouped.items(),
            key=lambda item: (self._manifest_recency(item[0]), str(item[0])),
            reverse=True,
        )
        for stem, twins in ordered:
            reason = self._flat_probe_disposition(twins)
            relative = _repo_relative(stem, self.repo_root)
            if reason is not None:
                self._record_skip(relative, "flat_twin", "skipped", reason)
            else:
                self._record_skip(
                    relative,
                    "flat_twin",
                    "not_selected",
                    f"a valid frame series was selected ({SELECTION_ORDER}); these flat "
                    "twins were not loaded and are NOT claimed validated in this mode",
                )

    def _load_snapshots_quarantined(self, lookup_ids: set[int]) -> tuple[Snapshot, ...]:
        candidates = _candidate_products(self.repo_root, self.product_argument)
        if not candidates:
            return ()
        grouped: dict[Path, dict[str, Path]] = {}
        for path in candidates:
            grouped.setdefault(path.with_suffix(""), {})[path.suffix.lower()] = path
        ordered = sorted(
            grouped.items(),
            key=lambda item: (self._manifest_recency(item[0]), str(item[0])),
            reverse=True,
        )
        loaded: list[Snapshot] = []
        seen_leads: dict[int, str] = {}
        for stem, twins in ordered:
            relative = _repo_relative(stem, self.repo_root)
            try:
                if set(twins) != {".csv", ".json"}:
                    raise ContractViolation(f"incomplete CSV/JSON twin pair for {relative}")
                csv_snapshot = _load_snapshot(
                    twins[".csv"],
                    repo_root=self.repo_root,
                    lookup_ids=lookup_ids,
                    contract_path=self.contract_path,
                    requirements=self.requirements,
                )
                json_snapshot = _load_snapshot(
                    twins[".json"],
                    repo_root=self.repo_root,
                    lookup_ids=lookup_ids,
                    contract_path=self.contract_path,
                    requirements=self.requirements,
                )
                csv_rows = [
                    {key: value for key, value in row.items() if key != "_geometry"}
                    for row in csv_snapshot.rows
                ]
                json_rows = [
                    {key: value for key, value in row.items() if key != "_geometry"}
                    for row in json_snapshot.rows
                ]
                if csv_rows != json_rows:
                    raise ContractViolation(f"CSV/JSON depth-product twins disagree for {relative}")
                lead = json_snapshot.lead_minutes
                if lead in seen_leads:
                    raise ContractViolation(
                        f"duplicate forecast_lead_minutes={lead}; the newer product "
                        f"{seen_leads[lead]} keeps this lead ({SELECTION_ORDER})"
                    )
            except (ContractViolation, OSError, json.JSONDecodeError) as exc:
                self._record_skip(relative, "flat_twin", "skipped", str(exc))
                continue
            seen_leads[lead] = relative
            loaded.append(json_snapshot)
        return tuple(sorted(loaded, key=lambda snapshot: snapshot.lead_minutes))

    @property
    def status(self) -> str:
        if self.error is not None:
            return "error"
        if self.series is not None:
            return "ready" if self.series.ready else "empty"
        return "ready" if self.snapshots else "empty"

    def state_payload(self) -> dict[str, Any]:
        candidate_outcome = {
            "skipped_candidates": list(self.skipped_candidates),
            "selection_order": SELECTION_ORDER,
        }
        if self.error is not None:
            return {
                "status": "error",
                "message": self.error,
                **candidate_outcome,
                "contract_gaps": list(CONTRACT_GAPS),
            }
        if self.series is not None:
            series_meta = self.series.meta_payload()
            if not series_meta["available"]:
                return {
                    "status": "empty",
                    "mode": "series",
                    "message": "The frame series could not be accepted: "
                    + str(series_meta["error"]),
                    "series": series_meta,
                    **candidate_outcome,
                    "contract_gaps": list(CONTRACT_GAPS),
                }
            gate = self._scientific_gate_summary()
            state = {
                "status": "ready",
                "mode": "series",
                "readiness_kind": "product_bytes_loaded_not_gate_acceptance",
                "message": "Contract-shaped frame series loaded; this is not gate acceptance.",
                "series": series_meta,
                **candidate_outcome,
                "geometry": {
                    "available": self.geometry.available,
                    "path": (
                        _repo_relative(self.geometry.path, self.repo_root)
                        if self.geometry.path is not None
                        else None
                    ),
                    "error": self.geometry.error,
                    "browser_scope": "bounded_preview_not_full_city",
                },
                "scientific_gate": gate,
                "contract": {
                    "name": self.contract.get("name"),
                    "version": self.contract.get("version"),
                    "path": "configs/contracts/depth_product.json",
                },
                "contract_gaps": list(CONTRACT_GAPS),
            }
            open_anomaly = self._open_anomaly_summary()
            if open_anomaly is not None:
                state["open_anomaly"] = open_anomaly
            return state
        if not self.snapshots:
            requested = (
                _repo_relative(self.product_argument, self.repo_root)
                if self.product_argument
                else None
            )
            message = (
                "No solver segment product is available. The dashboard is intentionally "
                "empty until a contract-valid depth product and source manifest exist."
            )
            return {
                "status": "empty",
                "message": message,
                "requested_product": requested,
                **candidate_outcome,
                "contract": {
                    "name": self.contract.get("name"),
                    "version": self.contract.get("version"),
                    "path": "configs/contracts/depth_product.json",
                },
                "contract_gaps": list(CONTRACT_GAPS),
            }
        gate = self._scientific_gate_summary()
        state = {
            "status": "ready",
            "readiness_kind": "product_bytes_loaded_not_gate_acceptance",
            "message": "Contract-valid product bytes are loaded; this is not gate acceptance.",
            "leads": [snapshot.lead_minutes for snapshot in self.snapshots],
            **candidate_outcome,
            "snapshots": [
                {
                    "lead_minutes": snapshot.lead_minutes,
                    "run_id": snapshot.run_id,
                    "product_path": _repo_relative(snapshot.path, self.repo_root),
                    "source_manifest_path": _repo_relative(snapshot.manifest_path, self.repo_root),
                    "manifest": snapshot.manifest_view,
                    "product_label": snapshot.manifest.get("product_label"),
                    "forcing_kind": snapshot.manifest.get("forcing_kind"),
                    "temporal_aggregation": snapshot.manifest.get("temporal_aggregation"),
                }
                for snapshot in self.snapshots
            ],
            "geometry": {
                "available": self.geometry.available,
                "path": (
                    _repo_relative(self.geometry.path, self.repo_root)
                    if self.geometry.path is not None
                    else None
                ),
                "error": self.geometry.error,
                "browser_scope": "bounded_preview_not_full_city",
            },
            "scientific_gate": gate,
            "contract": {
                "name": self.contract.get("name"),
                "version": self.contract.get("version"),
                "path": "configs/contracts/depth_product.json",
            },
            "contract_gaps": list(CONTRACT_GAPS),
        }
        open_anomaly = self._open_anomaly_summary()
        if open_anomaly is not None:
            state["open_anomaly"] = open_anomaly
        return state

    def _scientific_gate_summary(self) -> dict[str, Any]:
        if self.gate_report_argument is None:
            referenced = self._referenced_event_gate_summary()
            if referenced is not None:
                return referenced
            return {
                "status": "unavailable",
                "g1_status": "UNAVAILABLE",
                "signed_g3_status": "UNAVAILABLE",
                "reason": "no product-bound gate report configured",
            }
        try:
            path = _safe_repo_path(self.gate_report_argument, self.repo_root, label="gate report")
            payload = _load_json(path, label="gate report")
            if not isinstance(payload, dict):
                raise ContractViolation("gate report must be a JSON object")
            product_hashes: set[str] = set()
            for snapshot in self.snapshots:
                product_hashes.add(sha256_file(snapshot.path))
                csv_twin = snapshot.path.with_suffix(".csv")
                if csv_twin.is_file():
                    product_hashes.add(sha256_file(csv_twin))
            bound_hash = payload.get("input_sha256", {}).get("depth_product")
            if bound_hash not in product_hashes:
                raise ContractViolation("gate report is not bound to a selected product twin")
            event_scoped = any(
                snapshot.manifest.get("temporal_aggregation") == EVENT_MAXIMUM_AGGREGATION
                for snapshot in self.snapshots
            )
            raw_g1 = payload.get("g1", {}).get("status")
            return {
                "status": "loaded_not_accepted",
                "g1_status": _event_maximum_label(raw_g1) if event_scoped else raw_g1,
                "signed_g3_status": payload.get("g3", {}).get("status"),
                "bound_product_sha256": bound_hash,
                "report_path": _repo_relative(path, self.repo_root),
                "report_sha256": sha256_file(path),
                "scope": EVENT_MAXIMUM_SCOPE if event_scoped else "product_binding",
            }
        except (ContractViolation, DashboardError, OSError) as exc:
            referenced = self._referenced_event_gate_summary()
            if referenced is not None:
                return referenced
            return {
                "status": "invalid",
                "g1_status": "UNAVAILABLE",
                "signed_g3_status": "UNAVAILABLE",
                "reason": str(exc),
            }

    def _referenced_event_gate_summary(self) -> dict[str, Any] | None:
        if self.series is None:
            return None
        ref = self.series.manifest.get("event_maximum_gate_reference")
        if not isinstance(ref, dict):
            return None
        try:
            raw_path = ref.get("gate_report_path")
            if not isinstance(raw_path, str) or not raw_path.strip():
                raise ContractViolation("annotation carries no gate_report_path")
            path = _safe_repo_path(Path(raw_path), self.repo_root, label="annotated gate report")
            payload = _load_json(path, label="annotated gate report")
            if not isinstance(payload, dict):
                raise ContractViolation("annotated gate report must be a JSON object")
            realized_sha = sha256_file(path)
            return {
                "status": "loaded_not_accepted",
                "g1_status": _event_maximum_label(payload.get("g1", {}).get("status")),
                "signed_g3_status": payload.get("g3", {}).get("status"),
                "bound_product_sha256": ref.get("event_product_sha256"),
                "report_path": _repo_relative(path, self.repo_root),
                "report_sha256": realized_sha,
                "reference_stale": realized_sha != ref.get("gate_report_sha256"),
                "scope": ref.get("scope"),
            }
        except (ContractViolation, DashboardError, OSError) as exc:
            return {
                "status": "invalid",
                "g1_status": "UNAVAILABLE",
                "signed_g3_status": "UNAVAILABLE",
                "reason": f"event_maximum_gate_reference unusable: {exc}",
            }

    def _open_anomaly_summary(self) -> dict[str, Any] | None:
        "The ACTIVE run manifest's flagged unexplained result, verbatim (M3). Sourced only from producer/adjudicator-written normalized blocks -- ``open_anomaly`` (frames_v2 producer / carryover annotation) or ``owner_adjudication.open_anomaly`` (the adopted v6 record, the residual_anomaly equivalent for flat runs). A bare ``residual_anomaly`` block is deliberately NOT reshaped here: it lacks status/policy/range fields and inventing them would fabricate provenance. An incomplete or non-OPEN block renders nothing -- designed absence, never a partial card."  # noqa: E501
        if self.series is not None:
            manifest = self.series.manifest
            source_manifest = _repo_relative(self.series.manifest_path, self.repo_root)
        elif self.snapshots:
            snapshot = self.snapshots[-1]
            manifest = snapshot.manifest
            source_manifest = _repo_relative(snapshot.manifest_path, self.repo_root)
        else:
            return None
        block = manifest.get("open_anomaly")
        if not isinstance(block, dict):
            owner = manifest.get("owner_adjudication")
            block = owner.get("open_anomaly") if isinstance(owner, dict) else None
        if not isinstance(block, dict) or block.get("status") != "OPEN":
            return None
        n_segments = block.get("n_segments_gt300cm")
        range_cm = block.get("range_cm")
        policy = block.get("policy")
        if not isinstance(range_cm, list) or len(range_cm) != 2:
            low = block.get("range_cm_low_bound_cm")
            high = block.get("range_cm_high_cm")
            range_cm = [low, high]
        if (
            not isinstance(n_segments, int)
            or isinstance(n_segments, bool)
            or not all(isinstance(bound, int) for bound in range_cm)
            or not isinstance(policy, str)
            or not policy
        ):
            return None
        return {
            "status": "OPEN",
            "n_segments_gt300cm": n_segments,
            "range_cm": list(range_cm),
            "policy": policy,
            "source_manifest": source_manifest,
        }

    def product_blob(self, lead: int | None = None) -> bytes:

        import numpy as np

        snapshot = self._snapshot(lead)
        rows = snapshot.rows
        n = len(rows)
        ids = np.fromiter((row["segment_id"] for row in rows), dtype="<u4", count=n)
        dense = n > 0 and bool(np.array_equal(ids, np.arange(1, n + 1, dtype="<u4")))
        band_low = np.fromiter((row["band_low_cm"] for row in rows), dtype="<u2", count=n)
        band_high = np.fromiter((row["band_high_cm"] for row in rows), dtype="<u2", count=n)
        status_code = {"not_flooded": 0, "flooded": 1, "unknown": 2}
        status = np.fromiter(
            (status_code[row["flood_status"]] for row in rows), dtype="u1", count=n
        )
        header = np.asarray([n, 1 if dense else 0, snapshot.lead_minutes], dtype="<i4").tobytes()
        parts = [header]
        if not dense:
            parts.append(ids.tobytes())
        parts.extend((band_low.tobytes(), band_high.tobytes(), status.tobytes()))
        return b"".join(parts)

    def _snapshot(self, lead: int | None) -> Snapshot:
        if not self.snapshots:
            raise DashboardError("no contract-valid solver output is available")
        if lead is None:
            return self.snapshots[0]
        for snapshot in self.snapshots:
            if snapshot.lead_minutes == lead:
                return snapshot
        raise DashboardError(f"no realized product exists for forecast lead {lead}")

    def series_frame_blob(self, index: int) -> bytes:
        try:
            return self.series.frame_blob(index)
        except Exception as exc:
            raise DashboardError(str(exc)) from exc

    def series_segment_payload(self, index: int, segment_id: int) -> dict[str, Any]:
        row = self.series.lookup_segment(index, segment_id)
        if row is None:
            raise DashboardError(
                f"segment_id {segment_id} absent from frame {index} of the realized series"
            )
        geometry = (
            self.geometry.for_ids([segment_id]).get(segment_id) if self.geometry.available else None
        )
        series_meta = self.series.meta_payload()
        frame = series_meta["frames"][index]
        return {
            "type": "FeatureCollection",
            "mode": "series",
            "frame_index": index,
            "frame_tag": frame["tag"],
            "valid_time_utc": frame["valid_time_utc"],
            "source_manifest_path": series_meta["manifest_path"],
            "manifest": {
                "product_label": series_meta["product_label"],
                "run_id": series_meta["run_id"],
                "manifest_sha256": series_meta["manifest_sha256"],
            },
            "geometry": {
                "available": geometry is not None,
                "source_path": (
                    _repo_relative(self.geometry.path, self.repo_root)
                    if self.geometry.path is not None
                    else None
                ),
                "crs": self.geometry.crs,
                "scope": "requested_segment",
            },
            "features": [
                {
                    "type": "Feature",
                    "id": str(segment_id),
                    "geometry": geometry,
                    "properties": row,
                }
            ],
        }

    def segments_payload(
        self,
        lead: int | None = None,
        *,
        segment_id: int | None = None,
        offset: int = 0,
        limit: int | None = None,
    ) -> dict[str, Any]:
        snapshot = self._snapshot(lead)
        rows = snapshot.rows
        if segment_id is not None:
            rows = tuple(row for row in rows if row["segment_id"] == segment_id)
            if not rows:
                raise DashboardError(
                    f"segment_id {segment_id} is not present in the realized product"
                )
        elif self.geometry.available:
            if limit is None:
                raise DashboardError(
                    "geometry-backed segment requests must be bounded with limit; "
                    "full-city SVG/JSON rendering is refused"
                )
            if not 1 <= limit <= MAX_GEOMETRY_PREVIEW_FEATURES:
                raise DashboardError(
                    f"query parameter limit must be within 1..{MAX_GEOMETRY_PREVIEW_FEATURES}"
                )
            if offset < 0:
                raise DashboardError("query parameter offset must be non-negative")
        rows = rows[offset:] if limit is None else rows[offset : offset + limit]
        if not rows:
            raise DashboardError(
                f"query parameter offset selects no realized rows (row count {len(snapshot.rows)})"
            )

        geometry_by_id = {}
        row_geometries = {
            row["segment_id"]: row["_geometry"] for row in rows if row.get("_geometry") is not None
        }
        if row_geometries:
            geometry_by_id.update(row_geometries)
        if self.geometry.available:
            geometry_by_id.update(self.geometry.for_ids(row["segment_id"] for row in rows))

        features = []
        for row in rows:
            properties = {key: value for key, value in row.items() if key != "_geometry"}
            features.append(
                {
                    "type": "Feature",
                    "id": str(row["segment_id"]),
                    "geometry": geometry_by_id.get(row["segment_id"]),
                    "properties": properties,
                }
            )
        return {
            "type": "FeatureCollection",
            "run_id": snapshot.run_id,
            "lead_minutes": snapshot.lead_minutes,
            "valid_time_utc": rows[0]["valid_time_utc"],
            "issue_time_utc": rows[0]["issue_time_utc"],
            "source_manifest_path": _repo_relative(snapshot.manifest_path, self.repo_root),
            "manifest": snapshot.manifest_view,
            "product_label": snapshot.manifest.get("product_label"),
            "forcing_kind": snapshot.manifest.get("forcing_kind"),
            "temporal_aggregation": snapshot.manifest.get("temporal_aggregation"),
            "geometry": {
                "available": bool(geometry_by_id),
                "source_path": (
                    _repo_relative(self.geometry.path, self.repo_root)
                    if self.geometry.path is not None
                    else None
                ),
                "crs": self.geometry.crs,
                "scope": (
                    "bounded_preview_not_full_city"
                    if self.geometry.available and segment_id is None
                    else "requested_segment"
                ),
            },
            "features": features,
        }


def _json_response(handler: BaseHTTPRequestHandler, status: int, payload: dict[str, Any]) -> None:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(body)))
    handler.send_header("Cache-Control", "no-store")
    handler.end_headers()
    handler.wfile.write(body)


class DashboardHTTPServer(ThreadingHTTPServer):
    "Threading server carrying immutable dashboard dependencies."

    def __init__(self, address: tuple[str, int], store: DashboardStore) -> None:
        super().__init__(address, DashboardHandler)
        self.store = store


class DashboardHandler(BaseHTTPRequestHandler):
    server: DashboardHTTPServer

    def _serve_static(self, path: str) -> None:
        relative = "index.html" if path in {"", "/"} else unquote(path.lstrip("/"))
        candidate = (STATIC_ROOT / relative).resolve()
        try:
            candidate.relative_to(STATIC_ROOT.resolve())
        except ValueError:
            _json_response(self, HTTPStatus.NOT_FOUND, {"error": "not found"})
            return
        if not candidate.is_file():
            _json_response(self, HTTPStatus.NOT_FOUND, {"error": "not found"})
            return
        try:
            body = candidate.read_bytes()
        except OSError as exc:
            _json_response(self, HTTPStatus.INTERNAL_SERVER_ERROR, {"error": str(exc)})
            return
        content_type = mimetypes.guess_type(candidate.name)[0] or "application/octet-stream"
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", f"{content_type}; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        self.wfile.write(body)

    def _serve_context_asset(self, name: str) -> None:
        content_type = CONTEXT_ASSET_TYPES.get(name)
        if content_type is None:
            _json_response(
                self, HTTPStatus.NOT_FOUND, {"error": f"context asset not served: {name}"}
            )
            return
        path = CONTEXT_ASSET_ALT_PATHS.get(name) or (CONTEXT_DIR / name)
        try:
            body = path.read_bytes()
        except OSError as exc:
            _json_response(
                self,
                HTTPStatus.SERVICE_UNAVAILABLE,
                {"error": f"context asset unavailable: {name}: {exc}"},
            )
            return
        self.send_response(HTTPStatus.OK)
        if content_type == "application/json":
            self.send_header("Content-Type", "application/json; charset=utf-8")
        else:
            self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        self.wfile.write(body)

    def _serve_basemap_meta(self) -> None:
        if not BUNDLE.ensure():
            _json_response(self, HTTPStatus.SERVICE_UNAVAILABLE, {"error": BUNDLE.error})
            return
        gzip_if_accepted(
            self,
            json.dumps(BUNDLE.meta, separators=(",", ":")).encode("utf-8"),
            "application/json; charset=utf-8",
        )

    def _serve_basemap_blob(self, kind: str, name: str) -> None:
        if not BUNDLE.ensure():
            _json_response(self, HTTPStatus.SERVICE_UNAVAILABLE, {"error": BUNDLE.error})
            return
        try:
            if kind == "roads":
                blob = BUNDLE.road_bytes(name.removesuffix(".bin"))
                if blob is None:
                    raise BasemapError(f"unknown level of detail: {name}")
            elif kind == "lakes":
                blob = BUNDLE.lakes_bytes
            else:
                raise BasemapError(f"unknown basemap blob kind: {kind}")
        except BasemapError as exc:
            _json_response(self, HTTPStatus.NOT_FOUND, {"error": str(exc)})
            return
        gzip_if_accepted(self, blob, "application/octet-stream")

    def _serve_drains(self, name: str) -> None:
        snapshot = DRAIN_READER.get()
        if name == "meta":
            gzip_if_accepted(
                self,
                json.dumps(snapshot.meta_payload(), separators=(",", ":")).encode("utf-8"),
                "application/json; charset=utf-8",
            )
            return
        if not snapshot.available:
            _json_response(self, HTTPStatus.SERVICE_UNAVAILABLE, {"error": snapshot.reason})
            return
        import numpy as np

        if name == "edges.bin":
            header = np.asarray([snapshot.n_edges], dtype="<u4").tobytes()
            body = (
                header
                + np.asarray(snapshot.edge_offsets, dtype="<u4").tobytes()
                + np.asarray(snapshot.edge_coords, dtype="<f4").tobytes()
            )
            gzip_if_accepted(self, body, "application/octet-stream")
            return
        if name == "nodes.bin":
            header = np.asarray([snapshot.n_nodes], dtype="<u4").tobytes()
            body = (
                header
                + np.asarray(snapshot.node_ids, dtype="<u4").tobytes()
                + np.asarray(snapshot.node_xy, dtype="<f4").tobytes()
            )
            gzip_if_accepted(self, body, "application/octet-stream")
            return
        _json_response(self, HTTPStatus.NOT_FOUND, {"error": f"unknown drains path: {name}"})

    def do_GET(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler API
        request = urlsplit(self.path)
        if request.path == "/api/state":
            _json_response(self, HTTPStatus.OK, self.server.store.state_payload())
            return
        if request.path == "/api/product.bin":
            query = parse_qs(request.query)
            try:
                if self.server.store.series is not None:
                    index = _query_int(query, "index")
                    if index is None:
                        raise DashboardError("series mode requires the index parameter")
                    blob = self.server.store.series_frame_blob(index)
                else:
                    lead = _query_int(query, "lead")
                    blob = self.server.store.product_blob(lead)
            except DashboardError as exc:
                _json_response(self, HTTPStatus.CONFLICT, {"error": str(exc)})
                return
            gzip_if_accepted(self, blob, "application/octet-stream")
            return
        if request.path == "/api/replay_frame.bin":
            query = parse_qs(request.query)
            tag = (query.get("tag") or [""])[0].strip()
            if not _REPLAY_FRAME_TAG_RE.fullmatch(tag):
                _json_response(
                    self, HTTPStatus.BAD_REQUEST, {"error": f"invalid replay frame tag: {tag!r}"}
                )
                return
            try:
                replay = _replay_series()
                index = next((i for i, fr in enumerate(replay.frames) if fr.tag == tag), None)
                if index is None:
                    raise DashboardError(f"replay series declares no frame {tag}")
                with replay.lock:
                    if index not in replay.warm:
                        raise DashboardError(f"frame {tag} is not warm yet")
                blob = replay.frame_blob(index)
            except DashboardError as exc:
                _json_response(self, HTTPStatus.CONFLICT, {"error": str(exc)})
                return
            except Exception as exc:  # noqa: BLE001 - honest failure, never a guess
                _json_response(self, HTTPStatus.CONFLICT, {"error": f"{type(exc).__name__}: {exc}"})
                return
            gzip_if_accepted(self, blob, "application/octet-stream")
            return
        if request.path == "/api/basemap/meta":
            self._serve_basemap_meta()
            return
        if request.path.startswith("/api/basemap/roads/"):
            self._serve_basemap_blob("roads", request.path.removeprefix("/api/basemap/roads/"))
            return
        if request.path == "/api/basemap/lakes.bin":
            self._serve_basemap_blob("lakes", "lakes.bin")
            return
        if request.path == "/api/drains/causal":
            query = parse_qs(request.query)
            values = query.get("segment_id")
            segment_id = values[0].strip() if values and values[0] else ""
            if not segment_id:
                _json_response(
                    self,
                    HTTPStatus.BAD_REQUEST,
                    {"error": "causal lookup requires segment_id"},
                )
                return
            try:
                payload = DRAIN_READER.causal_for_segment(segment_id)
            except Exception as exc:  # noqa: BLE001 - honest failure, never a guess
                _json_response(
                    self,
                    HTTPStatus.SERVICE_UNAVAILABLE,
                    {"error": f"{type(exc).__name__}: {exc}"},
                )
                return
            _json_response(self, HTTPStatus.OK, payload)
            return
        if request.path.startswith("/api/drains/"):
            self._serve_drains(request.path.removeprefix("/api/drains/"))
            return
        if request.path.startswith("/api/context/"):
            self._serve_context_asset(request.path.removeprefix("/api/context/"))
            return
        if request.path in {"/api/watchlist", "/api/intersections"}:
            kind = request.path.rsplit("/", 1)[-1]
            query = parse_qs(request.query)
            frame_values = query.get("frame")
            frame_param = frame_values[0] if frame_values and frame_values[0] else "held"
            try:
                payload = _lane_payload(self.server.store, kind, frame_param)
            except DashboardError as exc:
                _json_response(self, HTTPStatus.SERVICE_UNAVAILABLE, {"error": str(exc)})
                return
            except Exception as exc:  # noqa: BLE001 - lane failure surfaces verbatim
                _json_response(
                    self,
                    HTTPStatus.SERVICE_UNAVAILABLE,
                    {"error": f"{type(exc).__name__}: {exc}"},
                )
                return
            _json_response(self, HTTPStatus.OK, payload)
            return
        if request.path == "/api/comparison2022":
            _serve_comparison(self)
            return
        if request.path == "/api/comparison2022/observed.json":
            _serve_comparison_observed(self)
            return
        if request.path == "/api/forecast/status":
            query = parse_qs(request.query)
            job_ids = query.get("job_id")
            job_id = job_ids[0].strip() if job_ids and job_ids[0] else ""
            if not job_id:
                _json_response(
                    self, HTTPStatus.BAD_REQUEST, {"error": "job_id query param required"}
                )
                return
            with LIVE_JOBS_LOCK:
                job = LIVE_JOBS.get(job_id)
                job_copy = dict(job) if job else None
            if job_copy is None:
                _json_response(self, HTTPStatus.NOT_FOUND, {"error": f"unknown job_id {job_id}"})
                return
            enriched = _live_manifest_authoritative(job_copy)
            if enriched.get("status") != job_copy.get("status"):
                with LIVE_JOBS_LOCK:
                    if job_id in LIVE_JOBS:
                        LIVE_JOBS[job_id].update(
                            {
                                k: enriched[k]
                                for k in (
                                    "status",
                                    "finished_utc",
                                    "wall_clock_s",
                                    "wall_clock_min",
                                    "steps",
                                    "manifest_status",
                                )
                                if k in enriched
                            }
                        )
            _json_response(self, HTTPStatus.OK, enriched)
            return
        if request.path == "/api/forecast/latest":
            with LIVE_JOBS_LOCK:
                jobs = list(LIVE_JOBS.values())
            if not jobs:
                _json_response(self, HTTPStatus.NOT_FOUND, {"error": "no live forecast jobs yet"})
                return
            terminal = [j for j in jobs if j.get("status") in ("completed", "failed")]
            chosen = None
            if terminal:
                chosen = max(
                    terminal, key=lambda j: j.get("finished_utc") or j.get("started_utc") or ""
                )
            else:
                chosen = max(jobs, key=lambda j: j.get("started_utc") or "")
            enriched = _live_manifest_authoritative(dict(chosen))
            _json_response(self, HTTPStatus.OK, enriched)
            return
        if request.path == "/api/segments":
            query = parse_qs(request.query)
            try:
                if self.server.store.series is not None:
                    index = _query_int(query, "index")
                    segment_id = _query_int(query, "segment_id")
                    if index is None or segment_id is None:
                        raise DashboardError("series mode requires index and segment_id parameters")
                    payload = self.server.store.series_segment_payload(index, segment_id)
                else:
                    lead = _query_int(query, "lead")
                    segment_id = _query_int(query, "segment_id")
                    offset = _query_int(query, "offset") or 0
                    limit = _query_int(query, "limit")
                    payload = self.server.store.segments_payload(
                        lead,
                        segment_id=segment_id,
                        offset=offset,
                        limit=limit,
                    )
            except DashboardError as exc:
                status = (
                    HTTPStatus.BAD_REQUEST if "query parameter" in str(exc) else HTTPStatus.CONFLICT
                )
                _json_response(self, status, {"error": str(exc)})
                return
            _json_response(self, HTTPStatus.OK, payload)
            return
        if request.path == "/api/ward_analysis":
            query = parse_qs(request.query)
            ward_name = (query.get("ward") or [""])[0].strip()
            index = _query_int(query, "index")
            series = self.server.store.series
            if not ward_name or series is None or not series.ready:
                _json_response(
                    self,
                    HTTPStatus.CONFLICT,
                    {"error": "ward_analysis requires ward and an active frame series"},
                )
                return
            if index is None:
                index = 0
            if index < 0 or index >= len(series.frames):
                raise DashboardError(f"frame index {index} out of range")
            import numpy as np

            try:
                membership = _ward_membership()
            except DashboardError as exc:
                _json_response(self, HTTPStatus.CONFLICT, {"error": str(exc)})
                return
            ward_no = membership["name_to_no"].get(ward_name)
            if ward_no is None:
                _json_response(
                    self, HTTPStatus.NOT_FOUND, {"error": f"unknown ward: {ward_name!r}"}
                )
                return
            with series.lock:
                warm = series.warm.get(index)
            if warm is None:
                _json_response(
                    self, HTTPStatus.CONFLICT, {"error": f"frame {index} is not warm yet"}
                )
                return
            ward_mask = membership["ward_of_segment"][1:] == ward_no
            n_segments = int(ward_mask.sum())
            if n_segments == 0:
                _json_response(
                    self,
                    HTTPStatus.NOT_FOUND,
                    {"error": f"ward {ward_name!r} maps to no segments in the realized membership"},
                )
                return
            flooded_mask = ward_mask & (warm.status[: warm.band_high.size] == 1)
            n_flooded = int(flooded_mask.sum())
            deepest_idx = -1
            deepest_cm = 0
            if n_flooded:
                flooded_rows = np.flatnonzero(flooded_mask)
                deepest_idx = int(flooded_rows[int(warm.band_high[flooded_rows].argmax())])
                deepest_cm = int(warm.band_high[deepest_idx])
            peak_index = None
            peak_n = -1
            peak_time = None
            for fi in range(len(series.frames)):
                with series.lock:
                    fw = series.warm.get(fi)
                if fw is None:
                    continue
                fn = int(((fw.status[: fw.band_high.size] == 1) & ward_mask).sum())
                if fn > peak_n:
                    peak_n = fn
                    peak_index = fi
                    peak_time = series.frames[fi].valid_time_utc
            deepest_street = None
            if deepest_idx >= 0:
                deepest_street = membership["street_by_segment"].get(deepest_idx + 1)
            _json_response(
                self,
                HTTPStatus.OK,
                {
                    "kind": "ward_analysis",
                    "ward_name": ward_name,
                    "ward_no": ward_no,
                    "frame_index": index,
                    "frame_valid_time_utc": series.frames[index].valid_time_utc,
                    "n_segments": n_segments,
                    "n_flooded": n_flooded,
                    "flood_share": round(n_flooded / n_segments, 6),
                    "deepest_cm": deepest_cm if n_flooded else None,
                    "deepest_segment_id": deepest_idx + 1 if deepest_idx >= 0 else None,
                    "deepest_street": deepest_street,
                    "peak_frame_index": peak_index,
                    "peak_valid_time_utc": peak_time,
                    "peak_n_flooded": peak_n if peak_n >= 0 else None,
                    "provenance": {
                        "membership_path": "data/interim/context/segment_ward_2022.csv.gz",
                        "series_manifest_path": _repo_relative(series.manifest_path, REPO_ROOT),
                    },
                },
            )
            return
        if request.path == "/api/segment_series":
            query = parse_qs(request.query)
            segment_id = _query_int(query, "segment_id")
            series = self.server.store.series
            if segment_id is None or series is None:
                _json_response(
                    self,
                    HTTPStatus.CONFLICT,
                    {"error": "segment_series requires segment_id and an active frame series"},
                )
                return
            meta = series.meta_payload()
            frames_out = []
            first_flooded = None
            try:
                for index in range(len(series.frames)):
                    if index not in series.warm:
                        continue
                    row = series.lookup_segment(index, segment_id)
                    if row is None:
                        continue
                    status = row["flood_status"]
                    if status == "flooded" and first_flooded is None:
                        first_flooded = index
                    frames_out.append(
                        {
                            "index": index,
                            "tag": meta["frames"][index]["tag"],
                            "valid_time_utc": meta["frames"][index]["valid_time_utc"],
                            "flood_status": status,
                            "band_low_cm": row["band_low_cm"],
                            "band_high_cm": row["band_high_cm"],
                        }
                    )
            except DashboardError as exc:
                _json_response(self, HTTPStatus.CONFLICT, {"error": str(exc)})
                return
            horizon = meta["frames"][-1]["valid_time_utc"] if meta["frames"] else None
            _json_response(
                self,
                HTTPStatus.OK,
                {
                    "segment_id": segment_id,
                    "n_frames_served": len(frames_out),
                    "frames": frames_out,
                    "first_flooded_index": first_flooded,
                    "first_flooded_valid_time_utc": (
                        frames_out[first_flooded]["valid_time_utc"]
                        if first_flooded is not None and frames_out
                        else None
                    ),
                    "series_last_valid_time_utc": horizon,
                    "source_manifest_path": meta["manifest_path"],
                },
            )
            return
        self._serve_static(request.path)

    def do_POST(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler API
        request = urlsplit(self.path)
        if request.path == "/api/forecast/trigger":
            # the tile — the runner refuses unmeasured CPU compute budgets, so a trigger here could
            # only ever spawn a doomed job. Refuse
            cpu_forced = (
                os.environ.get("JALADHAR_CPU_ONLY", "").strip().lower() in {"1", "true", "yes"}
                or os.environ.get("CUDA_VISIBLE_DEVICES", "x").strip() == ""
            )
            if cpu_forced:
                body = json.dumps(
                    {
                        "error": (
                            "live refresh unavailable: this session was launched "
                            "CPU-forced (run_demo.sh); the tile runner refuses "
                            "unmeasured CPU compute budgets. Relaunch the dashboard "
                            "outside run_demo.sh (GPU session) to enable live refresh."
                        ),
                        "reason_code": "cpu_forced_session",
                    }
                ).encode("utf-8")
                self.send_response(HTTPStatus.CONFLICT)
                self.send_header("Content-Type", "application/json; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.send_header("Cache-Control", "no-store")
                self.end_headers()
                self.wfile.write(body)
                return
            if not LIVE_SINGLE_FLIGHT.acquire(blocking=False):
                body = json.dumps(
                    {
                        "error": "single-flight: another forecast is running",
                        "retry_after_seconds": 60,
                    }
                ).encode("utf-8")
                self.send_response(HTTPStatus.CONFLICT)
                self.send_header("Content-Type", "application/json; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.send_header("Cache-Control", "no-store")
                self.send_header("Retry-After", "60")
                self.end_headers()
                self.wfile.write(body)
                return
            now = time.time()
            last_ts = LIVE_LAST_START.get("ts")
            if last_ts is not None and (now - last_ts) < LIVE_COOLDOWN_S:
                remaining = int(LIVE_COOLDOWN_S - (now - last_ts)) + 1
                try:
                    LIVE_SINGLE_FLIGHT.release()
                except ValueError:
                    pass
                body = json.dumps(
                    {"error": f"cooldown: {remaining}s remaining", "retry_after_seconds": remaining}
                ).encode("utf-8")
                self.send_response(HTTPStatus.TOO_MANY_REQUESTS)
                self.send_header("Content-Type", "application/json; charset=utf-8")
                self.send_header("Content-Length", str(len(body)))
                self.send_header("Cache-Control", "no-store")
                self.send_header("Retry-After", str(remaining))
                self.end_headers()
                self.wfile.write(body)
                return
            job_id = uuid.uuid4().hex[:12]
            started_utc = datetime.now(UTC).isoformat().replace("+00:00", "Z")
            timestamp_slug = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
            out_dir = REPO_ROOT / f"runs/live_3h_{timestamp_slug}"
            base_out = out_dir
            counter = 0
            while out_dir.exists():
                counter += 1
                out_dir = Path(str(base_out) + f"_{counter}")
                if counter > 10:
                    out_dir = REPO_ROOT / f"runs/live_3h_{timestamp_slug}_{job_id}"
                    break
            LIVE_LAST_START["ts"] = now
            LIVE_LAST_START["iso"] = started_utc
            out_rel = (
                out_dir.relative_to(REPO_ROOT).as_posix()
                if out_dir.is_relative_to(REPO_ROOT)
                else str(out_dir)
            )
            manifest_rel = (
                (out_dir / "manifest.json").relative_to(REPO_ROOT).as_posix()
                if (out_dir / "manifest.json").is_relative_to(REPO_ROOT)
                else str(out_dir / "manifest.json")
            )
            job: dict[str, Any] = {
                "job_id": job_id,
                "status": "queued",
                "out_dir": out_rel,
                "out_dir_abs": str(out_dir),
                "manifest_path": manifest_rel,
                "started_utc": started_utc,
                "finished_utc": None,
                "error": None,
                "pid": None,
                "log_path": None,
                "tile": LIVE_TILE,
            }
            with LIVE_JOBS_LOCK:
                LIVE_JOBS[job_id] = job

            def _run_job(jid: str = job_id, od: Path = out_dir, jref: dict[str, Any] = job) -> None:
                try:
                    with LIVE_JOBS_LOCK:
                        if jid in LIVE_JOBS:
                            LIVE_JOBS[jid]["status"] = "running"
                    log_path = Path(tempfile.gettempdir()) / f"live_3h_{jid}.log"
                    with LIVE_JOBS_LOCK:
                        if jid in LIVE_JOBS:
                            LIVE_JOBS[jid]["log_path"] = str(log_path)
                    with open(log_path, "wb") as log_file:
                        proc = subprocess.Popen(
                            [
                                str(REPO_ROOT / ".venv/bin/python"),
                                "scripts/run_windowed_forecast_3h.py",
                                "--tile",
                                LIVE_TILE,
                                "--out",
                                str(od),
                                "--dirty-tree-reason",
                                "live-refresh tile verification — tree dirtied by live wiring (app.py+live.js), recorded-not-laundered",  # noqa: E501
                            ],
                            cwd=str(REPO_ROOT),
                            stdout=log_file,
                            stderr=subprocess.STDOUT,
                        )
                        with LIVE_JOBS_LOCK:
                            if jid in LIVE_JOBS:
                                LIVE_JOBS[jid]["pid"] = proc.pid
                        proc.wait()
                        exit_code = proc.returncode
                    if exit_code != 0:
                        tail = ""
                        try:
                            text_log = log_path.read_text(encoding="utf-8", errors="ignore")
                            tail = text_log[-2000:]
                            snippet = tail[-400:].strip() if tail else f"process exited {exit_code}"
                        except Exception:
                            snippet = f"process exited {exit_code}"
                        with LIVE_JOBS_LOCK:
                            if jid in LIVE_JOBS:
                                LIVE_JOBS[jid]["status"] = "failed"
                                LIVE_JOBS[jid]["error"] = snippet[:400]
                                LIVE_JOBS[jid]["finished_utc"] = (
                                    datetime.now(UTC).isoformat().replace("+00:00", "Z")
                                )
                    else:
                        manifest_path = od / "manifest.json"
                        final_status = "completed"
                        try:
                            if manifest_path.is_file():
                                m = json.loads(manifest_path.read_text(encoding="utf-8"))
                                final_status = m.get("status", "completed")
                        except Exception:
                            pass
                        with LIVE_JOBS_LOCK:
                            if jid in LIVE_JOBS:
                                LIVE_JOBS[jid]["status"] = (
                                    final_status
                                    if final_status in ("completed", "failed")
                                    else "completed"
                                )
                                if LIVE_JOBS[jid]["status"] == "failed" and not LIVE_JOBS[jid].get(
                                    "error"
                                ):
                                    LIVE_JOBS[jid]["error"] = "manifest reports failed"
                                LIVE_JOBS[jid]["finished_utc"] = (
                                    datetime.now(UTC).isoformat().replace("+00:00", "Z")
                                )
                except Exception as exc:  # noqa: BLE001
                    with LIVE_JOBS_LOCK:
                        if jid in LIVE_JOBS:
                            LIVE_JOBS[jid]["status"] = "failed"
                            LIVE_JOBS[jid]["error"] = f"{type(exc).__name__}: {exc}"[:400]
                            LIVE_JOBS[jid]["finished_utc"] = (
                                datetime.now(UTC).isoformat().replace("+00:00", "Z")
                            )
                finally:
                    try:
                        LIVE_SINGLE_FLIGHT.release()
                    except ValueError:
                        pass

            thread = threading.Thread(target=_run_job, daemon=True)
            thread.start()
            body = json.dumps(
                {
                    "job_id": job_id,
                    "status": "queued",
                    "poll": f"/api/forecast/status?job_id={job_id}",
                }
            ).encode("utf-8")
            self.send_response(HTTPStatus.ACCEPTED)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)
            return
        _json_response(self, HTTPStatus.NOT_FOUND, {"error": "not found"})
        return

    def log_message(self, format: str, *args: Any) -> None:
        typer.echo(f"dashboard: {format % args}")


def _query_int(query: dict[str, list[str]], key: str) -> int | None:
    values = query.get(key)
    if not values or not values[0]:
        return None
    try:
        return int(values[0])
    except ValueError as exc:
        raise DashboardError(f"query parameter {key} must be an integer") from exc


def _check_static_assets() -> None:
    required = ("index.html", "app.js", "styles.css")
    for name in required:
        path = STATIC_ROOT / name
        if not path.is_file() or not path.read_text(encoding="utf-8").strip():
            raise DashboardError(f"required static asset is missing or empty: {path}")


def _print_check(store: DashboardStore) -> None:
    _check_static_assets()
    state = store.state_payload()
    typer.echo("CPU_ONLY_CHECK: PASS")
    typer.echo(f"contract_version: {store.contract.get('version')}")
    typer.echo(f"realized_product_state: {state['status']}")
    if state["status"] == "empty":
        typer.echo("empty_state_observable: no segment product discovered; zero features generated")
        typer.echo("fabricated_output: none")
    elif state["status"] == "ready":
        if state.get("mode") == "series":
            series = state["series"]
            typer.echo(f"series_run: {series['run_id']}")
            typer.echo(f"series_frames: {series['warm_frames']}/{series['n_frames']} warm")
            typer.echo(
                f"series_peak: {series['peak']['n_flooded']} flooded at "
                f"{series['peak']['valid_time_utc']}"
            )
            typer.echo(
                "contract_assertions: PASS (sha-verified frames, producer-count cross-check)"
            )
        else:
            typer.echo(f"realized_leads_minutes: {state['leads']}")
            typer.echo(f"snapshot_count: {len(store.snapshots)}")
            typer.echo("contract_assertions: PASS")
    else:
        raise DashboardError(cast(str, state.get("message", "dashboard input rejected")))


def _serve(store: DashboardStore, *, host: str, port: int) -> None:
    DRAIN_READER.geometry_provider = CAUSAL_MIDPOINTS.provide
    typer.echo(
        "dashboard: causal geometry_provider bound "
        f"(centreline midpoints available={CAUSAL_MIDPOINTS.available})"
    )
    server = DashboardHTTPServer((host, port), store)
    typer.echo(
        f"JALADHAR_DASHBOARD_READY host={host} port={server.server_port} "
        f"cpu_only=true product_state={store.status}"
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        typer.echo("JALADHAR_DASHBOARD_STOPPED")
    finally:
        server.server_close()


@app.command()
def check(
    product: Path | None = typer.Option(
        None,
        "--product",
        help=(
            "A segment_status CSV/JSON or products directory; omitted means discover realized runs."
        ),
    ),
    geometry: Path | None = typer.Option(
        None,
        "--geometry",
        help="Optional producer-supplied GeoPackage/GeoJSON segment geometry artifact.",
    ),
    gate_report: Path | None = typer.Option(
        None, "--gate-report", help="Optional product-bound G1/G3 report"
    ),
) -> None:

    try:
        store = DashboardStore(product=product, geometry=geometry, gate_report=gate_report)
        _print_check(store)
    except (DashboardError, ContractViolation) as exc:
        typer.echo(f"CPU_ONLY_CHECK: FAIL: {exc}", err=True)
        raise typer.Exit(code=1) from exc


@app.command()
def serve(
    host: str = typer.Option("127.0.0.1", "--host"),
    port: int = typer.Option(8503, "--port"),
    product: Path | None = typer.Option(
        None,
        "--product",
        help=(
            "A segment_status CSV/JSON or products directory; omitted means discover realized runs."
        ),
    ),
    geometry: Path | None = typer.Option(
        None,
        "--geometry",
        help="Optional producer-supplied GeoPackage/GeoJSON segment geometry artifact.",
    ),
    gate_report: Path | None = typer.Option(
        None, "--gate-report", help="Optional product-bound G1/G3 report"
    ),
) -> None:

    try:
        _check_static_assets()
        store = DashboardStore(product=product, geometry=geometry, gate_report=gate_report)
        _serve(store, host=host, port=port)
    except (DashboardError, ContractViolation) as exc:
        typer.echo(f"dashboard failed closed: {exc}", err=True)
        raise typer.Exit(code=1) from exc


if __name__ == "__main__":
    app()
