"""CPU-only read-only web dashboard for the frozen WF-3 depth product.

The dashboard is deliberately a product reader, not a solver adapter.  It will
serve an empty state until a producer has written a contract-valid segment
product and its source manifest.  No depth, status, geometry, or summary value
is generated by this module.

The HTTP surface is intentionally small:

* ``/`` serves the static dashboard;
* ``/api/state`` exposes the available immutable product snapshots;
* ``/api/segments`` exposes one selected snapshot as GeoJSON;
* ``/api/context/<name>`` serves allowlisted WF-6 context assets from
  ``data/interim/context/`` (wards blobs + meta sidecars, the segment->ward
  join, the search index, the forcing series);
* ``/api/watchlist`` and ``/api/intersections`` run the WF-6 lane builders
  against the store's active realized product (frame param: tag|index|"held");
* ``/api/drains/causal?segment_id=`` maps one street segment onto nearby
  predicted-overcapacity drain edges via an injected midpoint provider over
  the realized centreline GeoPackage.

Run the module with ``python -m jaladhar.web.app serve``.  ``check`` is a
CPU-only smoke check that does not create or mutate a run.
"""

from __future__ import annotations

import csv
import json
import mimetypes
import re
import threading
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, cast
from urllib.parse import parse_qs, unquote, urlsplit

import typer

from jaladhar.validation.depth_product_contract import (
    MAX_FORECAST_LEAD_MINUTES,
    DepthProductContractError,
    DepthProductRequirements,
    load_requirements,
    sha256_file,
    validate_product_manifest,
)
from jaladhar.web.basemap import BUNDLE, BasemapError, gzip_if_accepted
from jaladhar.web.drains import READER as DRAIN_READER
from jaladhar.web.intersections import build_intersections
from jaladhar.web.series import detect_series
from jaladhar.web.watchlist import build_watchlist, resolve_product_source

REPO_ROOT = Path(__file__).resolve().parents[3]
STATIC_ROOT = Path(__file__).resolve().parent / "static"
PRODUCT_FILE_RE = re.compile(r"segment_status(?:[_-].*)?\.(?:csv|json)$", re.IGNORECASE)
CONTRACT_GAPS = (
    "Road geometry is a separate realized artifact; the browser renders only a bounded preview "
    "and never claims full-city browser coverage.",
    "The frozen depth-product contract defines one product file per expected segment set, "
    "but does not define a multi-lead collection. The slider therefore exposes only lead "
    "values realized by supplied product files.",
    "Scientific gate status is read from a separately hash-bound report; product bytes loaded "
    "does not mean gate acceptance.",
)
MAX_GEOMETRY_PREVIEW_FEATURES = 2_000
# Recorded into every state payload that carries candidate outcomes (task U0b
# selection order): a valid frame series outranks valid flat event-maximum
# products because it realizes strictly more demonstrated state -- every replay
# frame plus the measured peak curve -- of which an event maximum is a summary;
# within each kind, producer-recorded completion time breaks ties newest-first.
SELECTION_ORDER = "frame_series_over_flat_event_maximum__newest_valid_first"

# Owner directive 2026-08-26: G1 asks "did the model flood this location during
# the event" -- an EVENT-level question.  The chip therefore reads the
# event-maximum score with an explicit scope suffix, never a bare status that
# could be mistaken for a per-frame/per-lead result, and never UNAVAILABLE
# while an event-level score exists to show.
EVENT_MAXIMUM_AGGREGATION = "event_maximum"
EVENT_MAXIMUM_SCOPE = "event_maximum"
EVENT_MAXIMUM_SUFFIX = " · event maximum"


def _event_maximum_label(raw: Any) -> Any:
    """Append the explicit event-maximum scope marker to a G1 display string.

    Non-string statuses pass through untouched so absent fields stay absent.
    """
    if isinstance(raw, str) and raw:
        return f"{raw}{EVENT_MAXIMUM_SUFFIX}"
    return raw


# ---- WF-6 context assets (U0f) ---------------------------------------------
# Strict allowlist: a request name must equal one of these literal filenames,
# so no path traversal is expressible (the served path is CONTEXT_DIR/name
# with name fixed by this table, never by the request beyond it).
CONTEXT_DIR = REPO_ROOT / "data" / "interim" / "context"
CONTEXT_ASSET_TYPES: dict[str, str] = {
    "wards_2022.bin": "application/octet-stream",
    "wards_2022.meta.json": "application/json",
    "wards_2023.bin": "application/octet-stream",
    "wards_2023.meta.json": "application/json",
    "segment_ward_2022.csv.gz": "application/gzip",
    "search_index.json": "application/json",
    "forcing_series.json": "application/json",
}

# Realized street-centreline artifact for the causal geometry provider.
ROAD_CENTRELINES_PATH = REPO_ROOT / "data" / "interim" / "terrain" / "roads_centrelines.gpkg"


class RoadMidpoints:
    """Lazy segment_id -> representative-point table over the realized
    centreline GeoPackage (drains.py's documented integrator injection point).

    Streams the GeoPackage ONCE on first use under a lock and keeps only ONE
    EPSG:32643 point per segment -- first vertex of the first part averaged
    with the last vertex of the last part, the same midpoint semantic rail.js
    applies client-side -- so 176k segments cost a small dict, not whole
    geometries. A failed read degrades to ``provide`` returning None; the
    causal payload then carries its designed honest empty state.
    """

    def __init__(self, path: Path) -> None:
        self.path = path
        self.lock = threading.Lock()
        self._points: dict[int, list[float]] | None = None
        self._error: str | None = None

    @property
    def available(self) -> bool:
        return self.path.is_file() and self._error is None

    def _load(self) -> None:
        if self._points is not None or self._error is not None:
            return
        if not self.path.is_file():
            self._error = f"centreline artifact missing: {self.path}"
            return
        try:
            import fiona

            points: dict[int, list[float]] = {}
            with fiona.open(self.path) as source:
                for feature in source:
                    properties = feature.get("properties") or {}
                    try:
                        segment_id = int(properties.get("segment_id"))
                    except (TypeError, ValueError):
                        continue
                    if segment_id in points:
                        continue
                    first = _geometry_first_vertex(feature.get("geometry"))
                    last = _geometry_last_vertex(feature.get("geometry"))
                    if first is None or last is None:
                        continue
                    points[segment_id] = [
                        (first[0] + last[0]) / 2.0,
                        (first[1] + last[1]) / 2.0,
                    ]
            if not points:
                raise DashboardError(f"centreline artifact yielded no midpoints: {self.path}")
            self._points = points
        except Exception as exc:  # noqa: BLE001 - degrade honestly, never guess
            self._error = f"{type(exc).__name__}: {exc}"

    def provide(self, segment_id: str | int) -> list[float] | None:
        with self.lock:
            self._load()
            points = self._points
        if points is None:
            return None
        try:
            point = points[int(segment_id)]
        except (TypeError, ValueError, KeyError):
            return None
        return [point[0], point[1]]


def _geometry_coordinates(geometry: Any) -> Any:
    """Coordinates of a GeoJSON-style geometry dict OR a fiona.model.Geometry
    (fiona >=1.10 hands out its own model objects, which are not dicts but do
    answer ``get("coordinates")``)."""
    if geometry is None:
        return None
    get = getattr(geometry, "get", None)
    if get is not None:
        try:
            return get("coordinates")
        except Exception:  # noqa: BLE001 - fall through to attribute access
            pass
    return getattr(geometry, "coordinates", None)


def _geometry_first_vertex(geometry: Any) -> tuple[float, float] | None:
    coords = _geometry_coordinates(geometry)
    while isinstance(coords, (list, tuple)) and coords and isinstance(coords[0], (list, tuple)):
        coords = coords[0]
    if (
        isinstance(coords, (list, tuple))
        and len(coords) >= 2
        and all(isinstance(v, (int, float)) for v in coords[:2])
    ):
        return (float(coords[0]), float(coords[1]))
    return None


def _geometry_last_vertex(geometry: Any) -> tuple[float, float] | None:
    coords = _geometry_coordinates(geometry)
    while isinstance(coords, (list, tuple)) and coords and isinstance(coords[-1], (list, tuple)):
        coords = coords[-1]
    if (
        isinstance(coords, (list, tuple))
        and len(coords) >= 2
        and all(isinstance(v, (int, float)) for v in coords[:2])
    ):
        return (float(coords[0]), float(coords[1]))
    return None


CAUSAL_MIDPOINTS = RoadMidpoints(ROAD_CENTRELINES_PATH)

# In-process cache for the lane builders, keyed by (kind, run_id, resolved
# frame). The builders re-read the centreline gpkg and product CSVs per call;
# caching per realized (run, frame) keeps repeated UI requests off that path.
_LANES_CACHE_LOCK = threading.Lock()
_LANES_CACHE: dict[tuple[str, str, str], dict[str, Any]] = {}


def _active_product_source(store: DashboardStore) -> Any:
    """Resolve the lane modules' ProductSource from the store's realized state.

    Series run dir when a ready frame series owns the store, else the flat
    products directory of the newest selected snapshot. No product -> honest
    refusal; nothing is built from absent state.
    """
    if store.series is not None and store.series.ready:
        return resolve_product_source(store.series.run_dir, repo_root=store.repo_root)
    if store.snapshots:
        products_dir = store.snapshots[-1].path.parent
        return resolve_product_source(products_dir, repo_root=store.repo_root)
    raise DashboardError("no realized depth product is loaded; watchlist/intersections refused")


def _resolve_lane_frame(source: Any, frame_param: str) -> tuple[Any, str]:
    """(lane frame value, cache-key suffix) from a tag|index|"held" param.

    "held" (the default, what watchlist.js pins until a frame event arrives)
    means the timeline's hold-at-end frame: the LAST frame of a series; flat
    sources have no frames, so the parameter is inert there.
    """
    raw = (frame_param or "").strip() or "held"
    if raw.lower() == "held":
        if getattr(source, "kind", "") == "frame" and source.frames:
            return len(source.frames) - 1, f"held:{source.frames[-1].tag}"
        return None, "flat"
    return raw, f"given:{raw}"


def _lane_payload(store: DashboardStore, kind: str, frame_param: str) -> dict[str, Any]:
    source = _active_product_source(store)
    frame_value, frame_key = _resolve_lane_frame(source, frame_param)
    cache_key = (kind, str(source.run_id), frame_key)
    with _LANES_CACHE_LOCK:
        cached = _LANES_CACHE.get(cache_key)
    if cached is not None:
        return cached
    if kind == "watchlist":
        payload = build_watchlist(source, frame_value, repo_root=store.repo_root)
    else:
        payload = build_intersections(source, frame_value, repo_root=store.repo_root)
    with _LANES_CACHE_LOCK:
        _LANES_CACHE[cache_key] = payload
    return payload


app = typer.Typer(add_completion=False, no_args_is_help=True)


class ContractViolation(ValueError):
    """A realized product failed a frozen producer-consumer assertion."""


class DashboardError(RuntimeError):
    """A dashboard input or static asset could not be served safely."""


def _repo_relative(path: Path, repo_root: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError:
        return str(path.resolve())


def _safe_repo_path(path: Path, repo_root: Path, *, label: str) -> Path:
    resolved = path.expanduser().resolve()
    try:
        resolved.relative_to(repo_root.resolve())
    except ValueError as exc:
        raise DashboardError(f"{label} must be inside the repository: {path}") from exc
    return resolved


def _parse_int(value: Any, *, field: str, row_number: int | None = None) -> int:
    location = f" at row {row_number}" if row_number is not None else ""
    if isinstance(value, bool):
        raise ContractViolation(f"{field}{location} must be an integer, not a boolean")
    if isinstance(value, int):
        return value
    if isinstance(value, str) and re.fullmatch(r"[+-]?\d+", value.strip()):
        return int(value.strip())
    raise ContractViolation(f"{field}{location} must be an integer")


def _parse_timestamp(value: Any, *, field: str, row_number: int) -> datetime:
    if not isinstance(value, str) or not value.strip():
        raise ContractViolation(f"{field} at row {row_number} must be an ISO8601 UTC timestamp")
    text = value.strip()
    if text.endswith("Z"):
        text = f"{text[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError as exc:
        raise ContractViolation(f"{field} at row {row_number} is not ISO8601: {value!r}") from exc
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise ContractViolation(f"{field} at row {row_number} must be timezone-aware UTC")
    if parsed.utcoffset() != UTC.utcoffset(parsed):
        raise ContractViolation(f"{field} at row {row_number} must carry a UTC offset")
    return parsed.astimezone(UTC)


def _load_json(path: Path, *, label: str) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ContractViolation(f"could not read {label} {path}: {exc}") from exc


def _contract(repo_root: Path) -> dict[str, Any]:
    path = repo_root / "configs" / "contracts" / "depth_product.json"
    payload = _load_json(path, label="frozen depth-product contract")
    if not isinstance(payload, dict):
        raise DashboardError(f"frozen depth-product contract is not an object: {path}")
    return cast(dict[str, Any], payload)


def _extract_product_rows(payload: Any, *, path: Path) -> list[dict[str, Any]]:
    """Accept the frozen JSON twin's common row/feature envelopes.

    The contract fixes fields, not whether the JSON twin is a bare row array or
    an API envelope.  Geometry is preserved only when the producer supplied it;
    it is never reconstructed from a segment id.
    """

    if isinstance(payload, list):
        raw_rows = payload
    elif isinstance(payload, dict) and isinstance(payload.get("features"), list):
        raw_rows = []
        for feature in payload["features"]:
            if not isinstance(feature, dict) or not isinstance(feature.get("properties"), dict):
                raise ContractViolation(f"JSON product feature has no properties object: {path}")
            row = dict(feature["properties"])
            if feature.get("geometry") is not None:
                row["_geometry"] = feature["geometry"]
            raw_rows.append(row)
    elif isinstance(payload, dict) and isinstance(payload.get("rows"), list):
        raw_rows = payload["rows"]
    elif isinstance(payload, dict) and isinstance(payload.get("segments"), list):
        raw_rows = payload["segments"]
    else:
        raise ContractViolation(
            f"JSON product {path} must be a row array, rows/segments envelope, or "
            "GeoJSON FeatureCollection"
        )

    rows: list[dict[str, Any]] = []
    for number, raw in enumerate(raw_rows, start=2):
        if not isinstance(raw, dict):
            raise ContractViolation(f"JSON product row {number} is not an object: {path}")
        rows.append(dict(raw))
    return rows


def _read_product_rows(path: Path) -> list[dict[str, Any]]:
    suffix = path.suffix.lower()
    if suffix == ".json":
        return _extract_product_rows(_load_json(path, label="depth product"), path=path)
    if suffix != ".csv":
        raise ContractViolation(f"unsupported depth-product format: {path.suffix}")
    try:
        with path.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            if reader.fieldnames is None:
                raise ContractViolation(f"CSV depth product has no header: {path}")
            rows = [dict(row) for row in reader]
    except OSError as exc:
        raise ContractViolation(f"could not read CSV depth product {path}: {exc}") from exc
    return rows


def _lookup_ids(repo_root: Path) -> set[int]:
    path = repo_root / "data" / "interim" / "terrain" / "roads_segment_lookup.csv"
    if not path.is_file():
        raise ContractViolation(
            f"required segment lookup is missing: {_repo_relative(path, repo_root)}"
        )
    try:
        with path.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            if reader.fieldnames is None or "segment_id" not in reader.fieldnames:
                raise ContractViolation(f"segment lookup has no segment_id column: {path}")
            ids: set[int] = set()
            for number, row in enumerate(reader, start=2):
                ids.add(
                    _parse_int(row.get("segment_id"), field="lookup.segment_id", row_number=number)
                )
    except OSError as exc:
        raise ContractViolation(f"could not read segment lookup {path}: {exc}") from exc
    if not ids:
        raise ContractViolation(f"segment lookup contains no realized ids: {path}")
    return ids


def _manifest_path(repo_root: Path, source_manifest: Any) -> Path:
    if not isinstance(source_manifest, str) or not source_manifest.strip():
        raise ContractViolation("source_manifest_path must be a non-empty repository-relative path")
    raw = Path(source_manifest)
    if raw.is_absolute() or ".." in raw.parts:
        raise ContractViolation("source_manifest_path must remain repository-relative")
    path = repo_root / raw
    try:
        path.resolve().relative_to(repo_root.resolve())
    except ValueError as exc:
        raise ContractViolation("source_manifest_path escapes the repository") from exc
    if not path.is_file():
        raise ContractViolation(f"source manifest does not exist: {source_manifest}")
    return path.resolve()


def _manifest_required(manifest: dict[str, Any], key: str, *, path: Path, repo_root: Path) -> Any:
    if key not in manifest:
        raise ContractViolation(
            f"source manifest {_repo_relative(path, repo_root)} lacks required field {key!r}"
        )
    return manifest[key]


def _validate_manifest(
    manifest: dict[str, Any],
    manifest_path: Path,
    *,
    repo_root: Path,
    run_id: str,
    rows: Sequence[dict[str, Any]],
    lookup_ids: set[int],
    contract_path: Path,
) -> dict[str, Any]:
    try:
        return validate_product_manifest(
            manifest,
            manifest_path,
            rows=rows,
            lookup_ids=lookup_ids,
            repo_root=repo_root,
            contract_path=contract_path,
        )
    except DepthProductContractError as exc:
        raise ContractViolation(str(exc)) from exc


def _normalize_row(
    row: dict[str, Any],
    *,
    number: int,
    repo_root: Path,
    requirements: DepthProductRequirements,
) -> dict[str, Any]:
    required = {
        "run_id",
        "segment_id",
        "band_low_cm",
        "band_high_cm",
        "confidence",
        "flood_status",
        "valid_time_utc",
        "issue_time_utc",
        "forecast_lead_minutes",
        "source_manifest_path",
    }
    missing = sorted(key for key in required if key not in row or row[key] in (None, ""))
    if missing:
        raise ContractViolation(f"depth product row {number} missing fields: {', '.join(missing)}")

    segment_id = _parse_int(row["segment_id"], field="segment_id", row_number=number)
    band_low = _parse_int(row["band_low_cm"], field="band_low_cm", row_number=number)
    band_high = _parse_int(row["band_high_cm"], field="band_high_cm", row_number=number)
    lead = _parse_int(
        row["forecast_lead_minutes"], field="forecast_lead_minutes", row_number=number
    )
    if segment_id < 1:
        raise ContractViolation(f"segment_id at row {number} must be positive")
    if band_low < 0 or band_high < 0 or band_low > band_high:
        raise ContractViolation(
            f"depth band at row {number} is not an ordered non-negative cm band"
        )
    if not 0 <= lead <= MAX_FORECAST_LEAD_MINUTES:
        raise ContractViolation(f"forecast_lead_minutes at row {number} must be within 0-180")

    confidence = str(row["confidence"])
    flood_status = str(row["flood_status"])
    if confidence not in {"modeled_direct", "modeled_interpolated", "no_data"}:
        raise ContractViolation(f"confidence at row {number} is not a frozen enum value")
    if confidence == "modeled_interpolated":
        raise ContractViolation(
            f"modeled_interpolated at row {number} is reserved and cannot be produced in v1"
        )
    if flood_status not in {"flooded", "not_flooded", "unknown"}:
        raise ContractViolation(f"flood_status at row {number} is not a frozen enum value")

    if confidence == "no_data":
        if flood_status != "unknown" or (band_low, band_high) != (0, 0):
            raise ContractViolation(
                f"no_data row {number} must be unknown with band [0, 0], got "
                f"{flood_status!r} [{band_low}, {band_high}]"
            )
    elif flood_status == "unknown":
        raise ContractViolation(f"modeled row {number} cannot have flood_status=unknown")
    if flood_status == "flooded" and band_high < requirements.flood_threshold_cm:
        raise ContractViolation(
            f"flooded row {number} has band_high_cm below the frozen flood rule"
        )

    valid_time = _parse_timestamp(row["valid_time_utc"], field="valid_time_utc", row_number=number)
    issue_time = _parse_timestamp(row["issue_time_utc"], field="issue_time_utc", row_number=number)
    if lead == 0 and issue_time < valid_time:
        raise ContractViolation(f"nowcast row {number} has issue_time_utc before valid_time_utc")
    if lead > 0 and issue_time > valid_time:
        raise ContractViolation(f"forecast row {number} has issue_time_utc after valid_time_utc")

    run_id = row["run_id"]
    if not isinstance(run_id, str) or not run_id.strip():
        raise ContractViolation(f"run_id at row {number} must be a non-empty string")
    source_manifest = row["source_manifest_path"]
    _manifest_path(repo_root, source_manifest)

    normalized = dict(row)
    normalized.update(
        {
            "run_id": run_id,
            "segment_id": segment_id,
            "band_low_cm": band_low,
            "band_high_cm": band_high,
            "confidence": confidence,
            "flood_status": flood_status,
            "valid_time_utc": valid_time.isoformat().replace("+00:00", "Z"),
            "issue_time_utc": issue_time.isoformat().replace("+00:00", "Z"),
            "forecast_lead_minutes": lead,
            "source_manifest_path": str(source_manifest),
        }
    )
    return normalized


@dataclass(frozen=True)
class Snapshot:
    """One contract-valid product file, representing one realized lead."""

    path: Path
    run_id: str
    lead_minutes: int
    rows: tuple[dict[str, Any], ...]
    manifest_path: Path
    manifest: dict[str, Any]
    manifest_view: dict[str, Any]


def _load_snapshot(
    path: Path,
    *,
    repo_root: Path,
    lookup_ids: set[int],
    contract_path: Path,
    requirements: DepthProductRequirements,
) -> Snapshot:
    raw_rows = _read_product_rows(path)
    if not raw_rows:
        raise ContractViolation(f"depth product is empty: {_repo_relative(path, repo_root)}")
    rows = tuple(
        _normalize_row(
            row,
            number=number,
            repo_root=repo_root,
            requirements=requirements,
        )
        for number, row in enumerate(raw_rows, start=2)
    )
    run_ids = {row["run_id"] for row in rows}
    if len(run_ids) != 1:
        raise ContractViolation("depth product contains more than one run_id")
    source_paths = {row["source_manifest_path"] for row in rows}
    if len(source_paths) != 1:
        raise ContractViolation("depth product contains more than one source_manifest_path")
    leads = {row["forecast_lead_minutes"] for row in rows}
    if len(leads) != 1:
        raise ContractViolation(
            "one product file contains more than one forecast lead; the frozen contract "
            "requires one row per expected segment set, so supply separate immutable files "
            "for the slider"
        )
    valid_times = {row["valid_time_utc"] for row in rows}
    issue_times = {row["issue_time_utc"] for row in rows}
    if len(valid_times) != 1 or len(issue_times) != 1:
        raise ContractViolation(
            "depth product snapshot metadata changes valid_time_utc or issue_time_utc "
            "within one product file"
        )
    ids = [row["segment_id"] for row in rows]
    if len(set(ids)) != len(ids):
        raise ContractViolation("depth product contains duplicate segment_id values")
    product_ids = set(ids)
    if product_ids != lookup_ids:
        missing = len(lookup_ids - product_ids)
        unexpected = len(product_ids - lookup_ids)
        raise ContractViolation(
            "product segment_id set disagrees with realized lookup "
            f"(missing={missing}, unexpected={unexpected})"
        )

    run_id = next(iter(run_ids))
    manifest_path = _manifest_path(repo_root, next(iter(source_paths)))
    manifest_payload = _load_json(manifest_path, label="source manifest")
    if not isinstance(manifest_payload, dict):
        raise ContractViolation(f"source manifest is not an object: {manifest_path}")
    manifest = cast(dict[str, Any], manifest_payload)
    manifest_view = _validate_manifest(
        manifest,
        manifest_path,
        repo_root=repo_root,
        run_id=run_id,
        rows=rows,
        lookup_ids=lookup_ids,
        contract_path=contract_path,
    )
    return Snapshot(
        path=path,
        run_id=run_id,
        lead_minutes=next(iter(leads)),
        rows=rows,
        manifest_path=manifest_path,
        manifest=manifest,
        manifest_view=manifest_view,
    )


def _candidate_products(repo_root: Path, product: Path | None) -> list[Path]:
    if product is not None:
        resolved = _safe_repo_path(product, repo_root, label="product")
        if not resolved.exists():
            return []
        if resolved.is_dir():
            return sorted(
                path
                for path in resolved.iterdir()
                if path.is_file() and PRODUCT_FILE_RE.fullmatch(path.name)
            )
        if resolved.is_file() and PRODUCT_FILE_RE.fullmatch(resolved.name):
            stem = resolved.with_suffix("")
            return sorted(
                path
                for path in (stem.with_suffix(".csv"), stem.with_suffix(".json"))
                if path.is_file()
            )
        raise DashboardError(
            f"product must be a segment_status CSV/JSON or its products directory: {product}"
        )

    candidates = [
        path for path in repo_root.glob("runs/**/products/segment_status*.csv") if path.is_file()
    ]
    candidates.extend(
        path for path in repo_root.glob("runs/**/products/segment_status*.json") if path.is_file()
    )
    return sorted(set(candidates))


class GeometryIndex:
    """Lazy reader for a producer-supplied segment geometry artifact."""

    def __init__(self, path: Path | None, *, repo_root: Path) -> None:
        self.path = path
        self.repo_root = repo_root
        self._features: dict[int, dict[str, Any]] | None = None
        self.crs: str | None = None
        self.error: str | None = None
        if path is not None:
            try:
                self.path = _safe_repo_path(path, repo_root, label="geometry")
                if not self.path.is_file():
                    raise DashboardError(f"geometry artifact does not exist: {path}")
            except (DashboardError, OSError) as exc:
                self.error = str(exc)

    @property
    def available(self) -> bool:
        return self.path is not None and self.error is None

    def _read(self) -> None:
        if self._features is not None or not self.available:
            return
        assert self.path is not None
        if self.path.suffix.lower() in {".json", ".geojson"}:
            payload = _load_json(self.path, label="geometry artifact")
            features = payload.get("features") if isinstance(payload, dict) else None
            if not isinstance(features, list):
                raise DashboardError(
                    f"geometry JSON is not a GeoJSON FeatureCollection: {self.path}"
                )
            result: dict[int, dict[str, Any]] = {}
            for feature in features:
                if not isinstance(feature, dict) or not isinstance(feature.get("properties"), dict):
                    continue
                raw_id = feature["properties"].get("segment_id", feature.get("id"))
                try:
                    segment_id = _parse_int(raw_id, field="geometry.segment_id")
                except ContractViolation:
                    continue
                if feature.get("geometry") is not None:
                    result[segment_id] = cast(dict[str, Any], feature["geometry"])
            self._features = result
            self.crs = "GeoJSON CRS (producer declaration not present in frozen product contract)"
            return

        try:
            import fiona
        except ImportError as exc:
            raise DashboardError(
                "fiona is required to read a GeoPackage geometry artifact"
            ) from exc
        try:
            layers = fiona.listlayers(self.path)
            if not layers:
                raise DashboardError(f"geometry GeoPackage has no layers: {self.path}")
            result = {}
            with fiona.open(self.path, layer=layers[0]) as source:
                self.crs = source.crs_wkt or str(source.crs) or None
                for feature in source:
                    properties = dict(feature.get("properties") or {})
                    raw_id = properties.get("segment_id", feature.get("id"))
                    try:
                        segment_id = _parse_int(raw_id, field="geometry.segment_id")
                    except ContractViolation:
                        continue
                    geometry = feature.get("geometry")
                    if geometry is not None:
                        result[segment_id] = dict(geometry)
        except (OSError, ValueError) as exc:
            raise DashboardError(f"could not read geometry artifact {self.path}: {exc}") from exc
        self._features = result

    def for_ids(self, ids: Iterable[int]) -> dict[int, dict[str, Any]]:
        self._read()
        if self._features is None:
            return {}
        return {
            segment_id: self._features[segment_id]
            for segment_id in ids
            if segment_id in self._features
        }


def _flat_probe_reason(twins: dict[str, Path], *, repo_root: Path) -> str | None:
    """Cheap series-mode disposition probe for one flat twin pair.

    Runs ONLY when a frame series owns the store and flat bytes will not be
    served: it reproduces the frozen contract's own small-file comparisons
    (twin completeness, completed status, uncoupled-baseline admission hash
    against realized admission bytes -- depth_product_contract's check inside
    ``validate_product_manifest``) without parsing 176k rows.  Returning None
    means "no cheap disqualifier", never "validated".
    """

    try:
        if set(twins) != {".csv", ".json"}:
            return "incomplete CSV/JSON twin pair"
        manifest_path = next(iter(twins.values())).parent.parent / "manifest.json"
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            return "run manifest is not an object"
        if payload.get("status") != "completed":
            return f"manifest status is {payload.get('status')!r}, not 'completed'"
        admission_relative = payload.get("uncoupled_baseline_admission_path")
        admission_sha = payload.get("uncoupled_baseline_admission_sha256")
        if isinstance(admission_relative, str) and isinstance(admission_sha, str):
            actual = sha256_file(repo_root / admission_relative)
            if actual != admission_sha:
                return (
                    "stale uncoupled_baseline_admission_sha256 "
                    f"{admission_sha[:12]}... vs realized admission bytes {actual[:12]}..."
                )
        return None
    except (ContractViolation, DashboardError, OSError, json.JSONDecodeError) as exc:
        return str(exc)


class DashboardStore:
    """Load and validate read-only depth products for the HTTP layer.

    Candidate quarantine: a candidate that fails validation (stale admission
    hash, incomplete twin, contract violation) is skipped with a stderr warning
    and recorded in ``skipped_candidates``; it never aborts the store while any
    other candidate validates.  ``status`` is ``error`` only when zero
    candidates validate and no frame series exists.
    """

    def __init__(
        self,
        *,
        repo_root: Path = REPO_ROOT,
        product: Path | None = None,
        geometry: Path | None = None,
        gate_report: Path | None = None,
    ) -> None:
        self.repo_root = repo_root.resolve()
        self.product_argument = product
        self.contract = _contract(self.repo_root)
        self.contract_path = self.repo_root / "configs" / "contracts" / "depth_product.json"
        self.requirements = load_requirements(self.contract_path)
        self.geometry = GeometryIndex(geometry, repo_root=self.repo_root)
        self.gate_report_argument = gate_report
        self.snapshots: tuple[Snapshot, ...] = ()
        self.error: str | None = None
        self.skipped_candidates: list[dict[str, str]] = []
        # A frame-series run (manifest with frames[]) takes over the store:
        # every frame realises forecast_lead_minutes=0, which the frozen
        # distinct-lead rule correctly refuses for a replay time series.
        self.series = detect_series(product, repo_root=self.repo_root)
        if self.series is not None:
            if product is None:
                # Cold discovery selected a series; annotate the flat twins it
                # outranks so operators see why they are not being served.
                self._annotate_flat_candidates()
            return
        try:
            lookup_ids = _lookup_ids(self.repo_root)
            self.snapshots = self._load_snapshots_quarantined(lookup_ids)
            if not self.snapshots and self.skipped_candidates:
                raise ContractViolation(
                    "no candidate depth product validated: "
                    + "; ".join(
                        f"{entry['candidate']}: {entry['reason']}"
                        for entry in self.skipped_candidates
                    )
                )
        except (ContractViolation, DashboardError, OSError, json.JSONDecodeError) as exc:
            self.error = str(exc)

    def _record_skip(self, candidate: str, kind: str, disposition: str, reason: str) -> None:
        self.skipped_candidates.append(
            {
                "candidate": candidate,
                "kind": kind,
                "disposition": disposition,
                "reason": reason,
            }
        )
        if disposition == "skipped":
            typer.echo(f"dashboard: skipped candidate {candidate}: {reason}", err=True)

    def _manifest_recency(self, stem: Path) -> tuple[str, str]:
        """Producer-recorded completion time used for newest-valid-first order."""

        manifest_path = stem.parent.parent / "manifest.json"
        try:
            payload = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return ("", "")
        if not isinstance(payload, dict):
            return ("", "")
        return (
            str(payload.get("end_time_iso") or payload.get("start_time_iso") or ""),
            "",
        )

    def _flat_probe_disposition(self, twins: dict[str, Path]) -> str | None:
        return _flat_probe_reason(twins, repo_root=self.repo_root)

    def _annotate_flat_candidates(self) -> None:
        candidates = _candidate_products(self.repo_root, None)
        grouped: dict[Path, dict[str, Path]] = {}
        for path in candidates:
            grouped.setdefault(path.with_suffix(""), {})[path.suffix.lower()] = path
        ordered = sorted(
            grouped.items(),
            key=lambda item: (self._manifest_recency(item[0]), str(item[0])),
            reverse=True,
        )
        for stem, twins in ordered:
            reason = self._flat_probe_disposition(twins)
            relative = _repo_relative(stem, self.repo_root)
            if reason is not None:
                self._record_skip(relative, "flat_twin", "skipped", reason)
            else:
                self._record_skip(
                    relative,
                    "flat_twin",
                    "not_selected",
                    f"a valid frame series was selected ({SELECTION_ORDER}); these flat "
                    "twins were not loaded and are NOT claimed validated in this mode",
                )

    def _load_snapshots_quarantined(self, lookup_ids: set[int]) -> tuple[Snapshot, ...]:
        candidates = _candidate_products(self.repo_root, self.product_argument)
        if not candidates:
            return ()
        grouped: dict[Path, dict[str, Path]] = {}
        for path in candidates:
            grouped.setdefault(path.with_suffix(""), {})[path.suffix.lower()] = path
        # Newest valid product wins: try candidates in producer-recorded
        # completion-time order so a newer valid product claims its lead first.
        ordered = sorted(
            grouped.items(),
            key=lambda item: (self._manifest_recency(item[0]), str(item[0])),
            reverse=True,
        )
        loaded: list[Snapshot] = []
        seen_leads: dict[int, str] = {}
        for stem, twins in ordered:
            relative = _repo_relative(stem, self.repo_root)
            try:
                if set(twins) != {".csv", ".json"}:
                    raise ContractViolation(f"incomplete CSV/JSON twin pair for {relative}")
                csv_snapshot = _load_snapshot(
                    twins[".csv"],
                    repo_root=self.repo_root,
                    lookup_ids=lookup_ids,
                    contract_path=self.contract_path,
                    requirements=self.requirements,
                )
                json_snapshot = _load_snapshot(
                    twins[".json"],
                    repo_root=self.repo_root,
                    lookup_ids=lookup_ids,
                    contract_path=self.contract_path,
                    requirements=self.requirements,
                )
                csv_rows = [
                    {key: value for key, value in row.items() if key != "_geometry"}
                    for row in csv_snapshot.rows
                ]
                json_rows = [
                    {key: value for key, value in row.items() if key != "_geometry"}
                    for row in json_snapshot.rows
                ]
                if csv_rows != json_rows:
                    raise ContractViolation(f"CSV/JSON depth-product twins disagree for {relative}")
                lead = json_snapshot.lead_minutes
                if lead in seen_leads:
                    raise ContractViolation(
                        f"duplicate forecast_lead_minutes={lead}; the newer product "
                        f"{seen_leads[lead]} keeps this lead ({SELECTION_ORDER})"
                    )
            except (ContractViolation, OSError, json.JSONDecodeError) as exc:
                self._record_skip(relative, "flat_twin", "skipped", str(exc))
                continue
            seen_leads[lead] = relative
            loaded.append(json_snapshot)
        return tuple(sorted(loaded, key=lambda snapshot: snapshot.lead_minutes))

    @property
    def status(self) -> str:
        if self.error is not None:
            return "error"
        if self.series is not None:
            return "ready" if self.series.ready else "empty"
        return "ready" if self.snapshots else "empty"

    def state_payload(self) -> dict[str, Any]:
        candidate_outcome = {
            "skipped_candidates": list(self.skipped_candidates),
            "selection_order": SELECTION_ORDER,
        }
        if self.error is not None:
            return {
                "status": "error",
                "message": self.error,
                **candidate_outcome,
                "contract_gaps": list(CONTRACT_GAPS),
            }
        if self.series is not None:
            series_meta = self.series.meta_payload()
            if not series_meta["available"]:
                return {
                    "status": "empty",
                    "mode": "series",
                    "message": "The frame series could not be accepted: "
                    + str(series_meta["error"]),
                    "series": series_meta,
                    **candidate_outcome,
                    "contract_gaps": list(CONTRACT_GAPS),
                }
            gate = self._scientific_gate_summary()
            state = {
                "status": "ready",
                "mode": "series",
                "readiness_kind": "product_bytes_loaded_not_gate_acceptance",
                "message": "Contract-shaped frame series loaded; this is not gate acceptance.",
                "series": series_meta,
                **candidate_outcome,
                "geometry": {
                    "available": self.geometry.available,
                    "path": (
                        _repo_relative(self.geometry.path, self.repo_root)
                        if self.geometry.path is not None
                        else None
                    ),
                    "error": self.geometry.error,
                    "browser_scope": "bounded_preview_not_full_city",
                },
                "scientific_gate": gate,
                "contract": {
                    "name": self.contract.get("name"),
                    "version": self.contract.get("version"),
                    "path": "configs/contracts/depth_product.json",
                },
                "contract_gaps": list(CONTRACT_GAPS),
            }
            open_anomaly = self._open_anomaly_summary()
            if open_anomaly is not None:
                state["open_anomaly"] = open_anomaly
            return state
        if not self.snapshots:
            requested = (
                _repo_relative(self.product_argument, self.repo_root)
                if self.product_argument
                else None
            )
            message = (
                "No solver segment product is available. The dashboard is intentionally "
                "empty until a contract-valid depth product and source manifest exist."
            )
            return {
                "status": "empty",
                "message": message,
                "requested_product": requested,
                **candidate_outcome,
                "contract": {
                    "name": self.contract.get("name"),
                    "version": self.contract.get("version"),
                    "path": "configs/contracts/depth_product.json",
                },
                "contract_gaps": list(CONTRACT_GAPS),
            }
        gate = self._scientific_gate_summary()
        state = {
            "status": "ready",
            "readiness_kind": "product_bytes_loaded_not_gate_acceptance",
            "message": "Contract-valid product bytes are loaded; this is not gate acceptance.",
            "leads": [snapshot.lead_minutes for snapshot in self.snapshots],
            **candidate_outcome,
            "snapshots": [
                {
                    "lead_minutes": snapshot.lead_minutes,
                    "run_id": snapshot.run_id,
                    "product_path": _repo_relative(snapshot.path, self.repo_root),
                    "source_manifest_path": _repo_relative(snapshot.manifest_path, self.repo_root),
                    "manifest": snapshot.manifest_view,
                    "product_label": snapshot.manifest.get("product_label"),
                    "forcing_kind": snapshot.manifest.get("forcing_kind"),
                    "temporal_aggregation": snapshot.manifest.get("temporal_aggregation"),
                }
                for snapshot in self.snapshots
            ],
            "geometry": {
                "available": self.geometry.available,
                "path": (
                    _repo_relative(self.geometry.path, self.repo_root)
                    if self.geometry.path is not None
                    else None
                ),
                "error": self.geometry.error,
                "browser_scope": "bounded_preview_not_full_city",
            },
            "scientific_gate": gate,
            "contract": {
                "name": self.contract.get("name"),
                "version": self.contract.get("version"),
                "path": "configs/contracts/depth_product.json",
            },
            "contract_gaps": list(CONTRACT_GAPS),
        }
        open_anomaly = self._open_anomaly_summary()
        if open_anomaly is not None:
            state["open_anomaly"] = open_anomaly
        return state

    def _scientific_gate_summary(self) -> dict[str, Any]:
        if self.gate_report_argument is None:
            referenced = self._referenced_event_gate_summary()
            if referenced is not None:
                return referenced
            return {
                "status": "unavailable",
                "g1_status": "UNAVAILABLE",
                "signed_g3_status": "UNAVAILABLE",
                "reason": "no product-bound gate report configured",
            }
        try:
            path = _safe_repo_path(self.gate_report_argument, self.repo_root, label="gate report")
            payload = _load_json(path, label="gate report")
            if not isinstance(payload, dict):
                raise ContractViolation("gate report must be a JSON object")
            product_hashes: set[str] = set()
            for snapshot in self.snapshots:
                product_hashes.add(sha256_file(snapshot.path))
                # The frozen contract enforces row-identical CSV/JSON twins at load, so a
                # gate report may bind either twin's bytes; realized reports bind the CSV.
                csv_twin = snapshot.path.with_suffix(".csv")
                if csv_twin.is_file():
                    product_hashes.add(sha256_file(csv_twin))
            bound_hash = payload.get("input_sha256", {}).get("depth_product")
            if bound_hash not in product_hashes:
                raise ContractViolation("gate report is not bound to a selected product twin")
            # Owner directive 2026-08-26: when the bound product IS an event
            # maximum, say so on the chip -- the score answers the event-level
            # question and must never read as a per-frame/per-lead result.
            event_scoped = any(
                snapshot.manifest.get("temporal_aggregation") == EVENT_MAXIMUM_AGGREGATION
                for snapshot in self.snapshots
            )
            raw_g1 = payload.get("g1", {}).get("status")
            return {
                "status": "loaded_not_accepted",
                "g1_status": _event_maximum_label(raw_g1) if event_scoped else raw_g1,
                "signed_g3_status": payload.get("g3", {}).get("status"),
                "bound_product_sha256": bound_hash,
                "report_path": _repo_relative(path, self.repo_root),
                "report_sha256": sha256_file(path),
                "scope": EVENT_MAXIMUM_SCOPE if event_scoped else "product_binding",
            }
        except (ContractViolation, DashboardError, OSError) as exc:
            # Direct binding failed; an annotated frame series still carries an
            # event-level score worth showing (owner rule: never UNAVAILABLE
            # when one exists).  Without a series, the failure is surfaced.
            referenced = self._referenced_event_gate_summary()
            if referenced is not None:
                return referenced
            return {
                "status": "invalid",
                "g1_status": "UNAVAILABLE",
                "signed_g3_status": "UNAVAILABLE",
                "reason": str(exc),
            }

    def _referenced_event_gate_summary(self) -> dict[str, Any] | None:
        """Event-maximum G1 via the series manifest's ``event_maximum_gate_reference``.

        Resolution order (b), owner directive 2026-08-26: G1 is an event-level
        question, so a frame series whose manifest was annotated by
        ``adjudicate_v6_adoption.py annotate-series-gate`` REFERENCES the
        event-maximum score instead of being rescoring per frame (prohibited).
        The recorded ``gate_report_sha256`` is checked against the report's
        CURRENT bytes: a mismatch marks ``reference_stale: true`` but the score
        is still loaded and exposed -- never UNAVAILABLE while an event-level
        score exists.  Returns None whenever no annotation applies so callers
        fall through to the direct-binding behaviour unchanged.
        """
        if self.series is None:
            return None
        ref = self.series.manifest.get("event_maximum_gate_reference")
        if not isinstance(ref, dict):
            return None
        try:
            raw_path = ref.get("gate_report_path")
            if not isinstance(raw_path, str) or not raw_path.strip():
                raise ContractViolation("annotation carries no gate_report_path")
            path = _safe_repo_path(Path(raw_path), self.repo_root, label="annotated gate report")
            payload = _load_json(path, label="annotated gate report")
            if not isinstance(payload, dict):
                raise ContractViolation("annotated gate report must be a JSON object")
            realized_sha = sha256_file(path)
            return {
                "status": "loaded_not_accepted",
                "g1_status": _event_maximum_label(payload.get("g1", {}).get("status")),
                "signed_g3_status": payload.get("g3", {}).get("status"),
                "bound_product_sha256": ref.get("event_product_sha256"),
                "report_path": _repo_relative(path, self.repo_root),
                "report_sha256": realized_sha,
                "reference_stale": realized_sha != ref.get("gate_report_sha256"),
                "scope": ref.get("scope"),
            }
        except (ContractViolation, DashboardError, OSError) as exc:
            # An unusable annotation degrades to the honest invalid state: the
            # score cannot be shown when its bytes are gone, and the reason
            # names the cause instead of a generic unavailable.
            return {
                "status": "invalid",
                "g1_status": "UNAVAILABLE",
                "signed_g3_status": "UNAVAILABLE",
                "reason": f"event_maximum_gate_reference unusable: {exc}",
            }

    def _open_anomaly_summary(self) -> dict[str, Any] | None:
        """The ACTIVE run manifest's flagged unexplained result, verbatim (M3).

        Sourced only from producer/adjudicator-written normalized blocks --
        ``open_anomaly`` (frames_v2 producer / carryover annotation) or
        ``owner_adjudication.open_anomaly`` (the adopted v6 record, the
        residual_anomaly equivalent for flat runs).  A bare ``residual_anomaly``
        block is deliberately NOT reshaped here: it lacks status/policy/range
        fields and inventing them would fabricate provenance.  An incomplete or
        non-OPEN block renders nothing -- designed absence, never a partial
        card.
        """
        if self.series is not None:
            manifest = self.series.manifest
            source_manifest = _repo_relative(self.series.manifest_path, self.repo_root)
        elif self.snapshots:
            # Same active-run rule as _active_product_source: newest selected snapshot.
            snapshot = self.snapshots[-1]
            manifest = snapshot.manifest
            source_manifest = _repo_relative(snapshot.manifest_path, self.repo_root)
        else:
            return None
        block = manifest.get("open_anomaly")
        if not isinstance(block, dict):
            owner = manifest.get("owner_adjudication")
            block = owner.get("open_anomaly") if isinstance(owner, dict) else None
        if not isinstance(block, dict) or block.get("status") != "OPEN":
            return None
        n_segments = block.get("n_segments_gt300cm")
        range_cm = block.get("range_cm")
        policy = block.get("policy")
        if not isinstance(range_cm, list) or len(range_cm) != 2:
            low = block.get("range_cm_low_bound_cm")
            high = block.get("range_cm_high_cm")
            range_cm = [low, high]
        if (
            not isinstance(n_segments, int)
            or isinstance(n_segments, bool)
            or not all(isinstance(bound, int) for bound in range_cm)
            or not isinstance(policy, str)
            or not policy
        ):
            return None
        return {
            "status": "OPEN",
            "n_segments_gt300cm": n_segments,
            "range_cm": list(range_cm),
            "policy": policy,
            "source_manifest": source_manifest,
        }

    def product_blob(self, lead: int | None = None) -> bytes:
        """Compact little-endian band arrays for one realised lead.

        Layout: ``n:u32, flags:u32, lead:i32``, then -- when segment ids are
        not exactly the dense range ``1..n`` (flags bit 0 clear) -- ``ids:u32``,
        followed always by ``band_low:u16[n], band_high:u16[n],
        status:u8[n]`` with status 0=not_flooded, 1=flooded, 2=unknown.
        Values are the already-validated snapshot rows; nothing is recomputed.
        """

        import numpy as np

        snapshot = self._snapshot(lead)
        rows = snapshot.rows
        n = len(rows)
        ids = np.fromiter((row["segment_id"] for row in rows), dtype="<u4", count=n)
        dense = n > 0 and bool(np.array_equal(ids, np.arange(1, n + 1, dtype="<u4")))
        band_low = np.fromiter((row["band_low_cm"] for row in rows), dtype="<u2", count=n)
        band_high = np.fromiter((row["band_high_cm"] for row in rows), dtype="<u2", count=n)
        status_code = {"not_flooded": 0, "flooded": 1, "unknown": 2}
        status = np.fromiter(
            (status_code[row["flood_status"]] for row in rows), dtype="u1", count=n
        )
        header = np.asarray([n, 1 if dense else 0, snapshot.lead_minutes], dtype="<i4").tobytes()
        parts = [header]
        if not dense:
            parts.append(ids.tobytes())
        parts.extend((band_low.tobytes(), band_high.tobytes(), status.tobytes()))
        return b"".join(parts)

    def _snapshot(self, lead: int | None) -> Snapshot:
        if not self.snapshots:
            raise DashboardError("no contract-valid solver output is available")
        if lead is None:
            return self.snapshots[0]
        for snapshot in self.snapshots:
            if snapshot.lead_minutes == lead:
                return snapshot
        raise DashboardError(f"no realized product exists for forecast lead {lead}")

    def series_frame_blob(self, index: int) -> bytes:
        try:
            return self.series.frame_blob(index)
        except Exception as exc:
            raise DashboardError(str(exc)) from exc

    def series_segment_payload(self, index: int, segment_id: int) -> dict[str, Any]:
        row = self.series.lookup_segment(index, segment_id)
        if row is None:
            raise DashboardError(
                f"segment_id {segment_id} absent from frame {index} of the realized series"
            )
        geometry = (
            self.geometry.for_ids([segment_id]).get(segment_id) if self.geometry.available else None
        )
        series_meta = self.series.meta_payload()
        frame = series_meta["frames"][index]
        return {
            "type": "FeatureCollection",
            "mode": "series",
            "frame_index": index,
            "frame_tag": frame["tag"],
            "valid_time_utc": frame["valid_time_utc"],
            "source_manifest_path": series_meta["manifest_path"],
            "manifest": {
                "product_label": series_meta["product_label"],
                "run_id": series_meta["run_id"],
                "manifest_sha256": series_meta["manifest_sha256"],
            },
            "geometry": {
                "available": geometry is not None,
                "source_path": (
                    _repo_relative(self.geometry.path, self.repo_root)
                    if self.geometry.path is not None
                    else None
                ),
                "crs": self.geometry.crs,
                "scope": "requested_segment",
            },
            "features": [
                {
                    "type": "Feature",
                    "id": str(segment_id),
                    "geometry": geometry,
                    "properties": row,
                }
            ],
        }

    def segments_payload(
        self,
        lead: int | None = None,
        *,
        segment_id: int | None = None,
        offset: int = 0,
        limit: int | None = None,
    ) -> dict[str, Any]:
        snapshot = self._snapshot(lead)
        rows = snapshot.rows
        if segment_id is not None:
            rows = tuple(row for row in rows if row["segment_id"] == segment_id)
            if not rows:
                raise DashboardError(
                    f"segment_id {segment_id} is not present in the realized product"
                )
        elif self.geometry.available:
            if limit is None:
                raise DashboardError(
                    "geometry-backed segment requests must be bounded with limit; "
                    "full-city SVG/JSON rendering is refused"
                )
            if not 1 <= limit <= MAX_GEOMETRY_PREVIEW_FEATURES:
                raise DashboardError(
                    f"query parameter limit must be within 1..{MAX_GEOMETRY_PREVIEW_FEATURES}"
                )
            if offset < 0:
                raise DashboardError("query parameter offset must be non-negative")
        rows = rows[offset:] if limit is None else rows[offset : offset + limit]
        if not rows:
            raise DashboardError(
                f"query parameter offset selects no realized rows (row count {len(snapshot.rows)})"
            )

        geometry_by_id = {}
        row_geometries = {
            row["segment_id"]: row["_geometry"] for row in rows if row.get("_geometry") is not None
        }
        if row_geometries:
            geometry_by_id.update(row_geometries)
        if self.geometry.available:
            geometry_by_id.update(self.geometry.for_ids(row["segment_id"] for row in rows))

        features = []
        for row in rows:
            properties = {key: value for key, value in row.items() if key != "_geometry"}
            features.append(
                {
                    "type": "Feature",
                    "id": str(row["segment_id"]),
                    "geometry": geometry_by_id.get(row["segment_id"]),
                    "properties": properties,
                }
            )
        return {
            "type": "FeatureCollection",
            "run_id": snapshot.run_id,
            "lead_minutes": snapshot.lead_minutes,
            "valid_time_utc": rows[0]["valid_time_utc"],
            "issue_time_utc": rows[0]["issue_time_utc"],
            "source_manifest_path": _repo_relative(snapshot.manifest_path, self.repo_root),
            "manifest": snapshot.manifest_view,
            "product_label": snapshot.manifest.get("product_label"),
            "forcing_kind": snapshot.manifest.get("forcing_kind"),
            "temporal_aggregation": snapshot.manifest.get("temporal_aggregation"),
            "geometry": {
                "available": bool(geometry_by_id),
                "source_path": (
                    _repo_relative(self.geometry.path, self.repo_root)
                    if self.geometry.path is not None
                    else None
                ),
                "crs": self.geometry.crs,
                "scope": (
                    "bounded_preview_not_full_city"
                    if self.geometry.available and segment_id is None
                    else "requested_segment"
                ),
            },
            "features": features,
        }


def _json_response(handler: BaseHTTPRequestHandler, status: int, payload: dict[str, Any]) -> None:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(body)))
    handler.send_header("Cache-Control", "no-store")
    handler.end_headers()
    handler.wfile.write(body)


class DashboardHTTPServer(ThreadingHTTPServer):
    """Threading server carrying immutable dashboard dependencies."""

    def __init__(self, address: tuple[str, int], store: DashboardStore) -> None:
        super().__init__(address, DashboardHandler)
        self.store = store


class DashboardHandler(BaseHTTPRequestHandler):
    server: DashboardHTTPServer

    def _serve_static(self, path: str) -> None:
        relative = "index.html" if path in {"", "/"} else unquote(path.lstrip("/"))
        candidate = (STATIC_ROOT / relative).resolve()
        try:
            candidate.relative_to(STATIC_ROOT.resolve())
        except ValueError:
            _json_response(self, HTTPStatus.NOT_FOUND, {"error": "not found"})
            return
        if not candidate.is_file():
            _json_response(self, HTTPStatus.NOT_FOUND, {"error": "not found"})
            return
        try:
            body = candidate.read_bytes()
        except OSError as exc:
            _json_response(self, HTTPStatus.INTERNAL_SERVER_ERROR, {"error": str(exc)})
            return
        content_type = mimetypes.guess_type(candidate.name)[0] or "application/octet-stream"
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", f"{content_type}; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        self.wfile.write(body)

    def _serve_context_asset(self, name: str) -> None:
        """Serve one allowlisted WF-6 context asset from data/interim/context.

        The name must equal an allowlist key verbatim, so the served path is
        CONTEXT_DIR joined with a literal filename -- traversal cannot reach
        outside that directory because nothing but exact names is accepted.
        Bytes go out exactly as produced (the .csv.gz stays gzip on the wire;
        no extra transport compression layering).
        """
        content_type = CONTEXT_ASSET_TYPES.get(name)
        if content_type is None:
            _json_response(
                self, HTTPStatus.NOT_FOUND, {"error": f"context asset not served: {name}"}
            )
            return
        path = CONTEXT_DIR / name
        try:
            body = path.read_bytes()
        except OSError as exc:
            _json_response(
                self,
                HTTPStatus.SERVICE_UNAVAILABLE,
                {"error": f"context asset unavailable: {name}: {exc}"},
            )
            return
        self.send_response(HTTPStatus.OK)
        if content_type == "application/json":
            self.send_header("Content-Type", "application/json; charset=utf-8")
        else:
            self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        self.wfile.write(body)

    def _serve_basemap_meta(self) -> None:
        if not BUNDLE.ensure():
            _json_response(self, HTTPStatus.SERVICE_UNAVAILABLE, {"error": BUNDLE.error})
            return
        gzip_if_accepted(
            self,
            json.dumps(BUNDLE.meta, separators=(",", ":")).encode("utf-8"),
            "application/json; charset=utf-8",
        )

    def _serve_basemap_blob(self, kind: str, name: str) -> None:
        if not BUNDLE.ensure():
            _json_response(self, HTTPStatus.SERVICE_UNAVAILABLE, {"error": BUNDLE.error})
            return
        try:
            if kind == "roads":
                blob = BUNDLE.road_bytes(name.removesuffix(".bin"))
                if blob is None:
                    raise BasemapError(f"unknown level of detail: {name}")
            elif kind == "lakes":
                blob = BUNDLE.lakes_bytes
            else:
                raise BasemapError(f"unknown basemap blob kind: {kind}")
        except BasemapError as exc:
            _json_response(self, HTTPStatus.NOT_FOUND, {"error": str(exc)})
            return
        gzip_if_accepted(self, blob, "application/octet-stream")

    def _serve_drains(self, name: str) -> None:
        snapshot = DRAIN_READER.get()
        if name == "meta":
            gzip_if_accepted(
                self,
                json.dumps(snapshot.meta_payload(), separators=(",", ":")).encode("utf-8"),
                "application/json; charset=utf-8",
            )
            return
        if not snapshot.available:
            _json_response(self, HTTPStatus.SERVICE_UNAVAILABLE, {"error": snapshot.reason})
            return
        import numpy as np

        if name == "edges.bin":
            header = np.asarray([snapshot.n_edges], dtype="<u4").tobytes()
            body = (
                header
                + np.asarray(snapshot.edge_offsets, dtype="<u4").tobytes()
                + np.asarray(snapshot.edge_coords, dtype="<f4").tobytes()
            )
            gzip_if_accepted(self, body, "application/octet-stream")
            return
        if name == "nodes.bin":
            header = np.asarray([snapshot.n_nodes], dtype="<u4").tobytes()
            body = (
                header
                + np.asarray(snapshot.node_ids, dtype="<u4").tobytes()
                + np.asarray(snapshot.node_xy, dtype="<f4").tobytes()
            )
            gzip_if_accepted(self, body, "application/octet-stream")
            return
        _json_response(self, HTTPStatus.NOT_FOUND, {"error": f"unknown drains path: {name}"})

    def do_GET(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler API
        request = urlsplit(self.path)
        if request.path == "/api/state":
            _json_response(self, HTTPStatus.OK, self.server.store.state_payload())
            return
        if request.path == "/api/product.bin":
            query = parse_qs(request.query)
            try:
                if self.server.store.series is not None:
                    index = _query_int(query, "index")
                    if index is None:
                        raise DashboardError("series mode requires the index parameter")
                    blob = self.server.store.series_frame_blob(index)
                else:
                    lead = _query_int(query, "lead")
                    blob = self.server.store.product_blob(lead)
            except DashboardError as exc:
                _json_response(self, HTTPStatus.CONFLICT, {"error": str(exc)})
                return
            gzip_if_accepted(self, blob, "application/octet-stream")
            return
        if request.path == "/api/basemap/meta":
            self._serve_basemap_meta()
            return
        if request.path.startswith("/api/basemap/roads/"):
            self._serve_basemap_blob("roads", request.path.removeprefix("/api/basemap/roads/"))
            return
        if request.path == "/api/basemap/lakes.bin":
            self._serve_basemap_blob("lakes", "lakes.bin")
            return
        if request.path == "/api/drains/causal":
            query = parse_qs(request.query)
            values = query.get("segment_id")
            segment_id = values[0].strip() if values and values[0] else ""
            if not segment_id:
                _json_response(
                    self,
                    HTTPStatus.BAD_REQUEST,
                    {"error": "causal lookup requires segment_id"},
                )
                return
            try:
                payload = DRAIN_READER.causal_for_segment(segment_id)
            except Exception as exc:  # noqa: BLE001 - honest failure, never a guess
                _json_response(
                    self,
                    HTTPStatus.SERVICE_UNAVAILABLE,
                    {"error": f"{type(exc).__name__}: {exc}"},
                )
                return
            _json_response(self, HTTPStatus.OK, payload)
            return
        if request.path.startswith("/api/drains/"):
            self._serve_drains(request.path.removeprefix("/api/drains/"))
            return
        if request.path.startswith("/api/context/"):
            self._serve_context_asset(request.path.removeprefix("/api/context/"))
            return
        if request.path in {"/api/watchlist", "/api/intersections"}:
            kind = request.path.rsplit("/", 1)[-1]
            query = parse_qs(request.query)
            frame_values = query.get("frame")
            frame_param = frame_values[0] if frame_values and frame_values[0] else "held"
            try:
                payload = _lane_payload(self.server.store, kind, frame_param)
            except DashboardError as exc:
                _json_response(self, HTTPStatus.SERVICE_UNAVAILABLE, {"error": str(exc)})
                return
            except Exception as exc:  # noqa: BLE001 - lane failure surfaces verbatim
                _json_response(
                    self,
                    HTTPStatus.SERVICE_UNAVAILABLE,
                    {"error": f"{type(exc).__name__}: {exc}"},
                )
                return
            _json_response(self, HTTPStatus.OK, payload)
            return
        if request.path == "/api/segments":
            query = parse_qs(request.query)
            try:
                if self.server.store.series is not None:
                    index = _query_int(query, "index")
                    segment_id = _query_int(query, "segment_id")
                    if index is None or segment_id is None:
                        raise DashboardError("series mode requires index and segment_id parameters")
                    payload = self.server.store.series_segment_payload(index, segment_id)
                else:
                    lead = _query_int(query, "lead")
                    segment_id = _query_int(query, "segment_id")
                    offset = _query_int(query, "offset") or 0
                    limit = _query_int(query, "limit")
                    payload = self.server.store.segments_payload(
                        lead,
                        segment_id=segment_id,
                        offset=offset,
                        limit=limit,
                    )
            except DashboardError as exc:
                status = (
                    HTTPStatus.BAD_REQUEST if "query parameter" in str(exc) else HTTPStatus.CONFLICT
                )
                _json_response(self, status, {"error": str(exc)})
                return
            _json_response(self, HTTPStatus.OK, payload)
            return
        self._serve_static(request.path)

    def log_message(self, format: str, *args: Any) -> None:
        # Keep the dashboard's terminal output useful for a demo rehearsal.
        typer.echo(f"dashboard: {format % args}")


def _query_int(query: dict[str, list[str]], key: str) -> int | None:
    values = query.get(key)
    if not values or not values[0]:
        return None
    try:
        return int(values[0])
    except ValueError as exc:
        raise DashboardError(f"query parameter {key} must be an integer") from exc


def _check_static_assets() -> None:
    required = ("index.html", "app.js", "styles.css")
    for name in required:
        path = STATIC_ROOT / name
        if not path.is_file() or not path.read_text(encoding="utf-8").strip():
            raise DashboardError(f"required static asset is missing or empty: {path}")


def _print_check(store: DashboardStore) -> None:
    _check_static_assets()
    state = store.state_payload()
    typer.echo("CPU_ONLY_CHECK: PASS")
    typer.echo(f"contract_version: {store.contract.get('version')}")
    typer.echo(f"realized_product_state: {state['status']}")
    if state["status"] == "empty":
        typer.echo("empty_state_observable: no segment product discovered; zero features generated")
        typer.echo("fabricated_output: none")
    elif state["status"] == "ready":
        if state.get("mode") == "series":
            series = state["series"]
            typer.echo(f"series_run: {series['run_id']}")
            typer.echo(f"series_frames: {series['warm_frames']}/{series['n_frames']} warm")
            typer.echo(
                f"series_peak: {series['peak']['n_flooded']} flooded at "
                f"{series['peak']['valid_time_utc']}"
            )
            typer.echo(
                "contract_assertions: PASS (sha-verified frames, producer-count cross-check)"
            )
        else:
            typer.echo(f"realized_leads_minutes: {state['leads']}")
            typer.echo(f"snapshot_count: {len(store.snapshots)}")
            typer.echo("contract_assertions: PASS")
    else:
        raise DashboardError(cast(str, state.get("message", "dashboard input rejected")))


def _serve(store: DashboardStore, *, host: str, port: int) -> None:
    # WF-6 A5: bind the causal geometry provider to the realized centreline
    # artifact. Without it every causal payload degrades to the honest
    # none_measured empty state; with it, segment->flagged-edge proximity is
    # computed from produced bytes only.
    DRAIN_READER.geometry_provider = CAUSAL_MIDPOINTS.provide
    typer.echo(
        "dashboard: causal geometry_provider bound "
        f"(centreline midpoints available={CAUSAL_MIDPOINTS.available})"
    )
    server = DashboardHTTPServer((host, port), store)
    typer.echo(
        f"JALADHAR_DASHBOARD_READY host={host} port={server.server_port} "
        f"cpu_only=true product_state={store.status}"
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        typer.echo("JALADHAR_DASHBOARD_STOPPED")
    finally:
        server.server_close()


@app.command()
def check(
    product: Path | None = typer.Option(
        None,
        "--product",
        help=(
            "A segment_status CSV/JSON or products directory; omitted means discover realized runs."
        ),
    ),
    geometry: Path | None = typer.Option(
        None,
        "--geometry",
        help="Optional producer-supplied GeoPackage/GeoJSON segment geometry artifact.",
    ),
    gate_report: Path | None = typer.Option(
        None, "--gate-report", help="Optional product-bound G1/G3 report"
    ),
) -> None:
    """Run a CPU-only dashboard check without creating a run or solver output."""

    try:
        store = DashboardStore(product=product, geometry=geometry, gate_report=gate_report)
        _print_check(store)
    except (DashboardError, ContractViolation) as exc:
        typer.echo(f"CPU_ONLY_CHECK: FAIL: {exc}", err=True)
        raise typer.Exit(code=1) from exc


@app.command()
def serve(
    host: str = typer.Option("127.0.0.1", "--host"),
    port: int = typer.Option(8503, "--port"),
    product: Path | None = typer.Option(
        None,
        "--product",
        help=(
            "A segment_status CSV/JSON or products directory; omitted means discover realized runs."
        ),
    ),
    geometry: Path | None = typer.Option(
        None,
        "--geometry",
        help="Optional producer-supplied GeoPackage/GeoJSON segment geometry artifact.",
    ),
    gate_report: Path | None = typer.Option(
        None, "--gate-report", help="Optional product-bound G1/G3 report"
    ),
) -> None:
    """Serve the read-only web GIS dashboard on CPU."""

    try:
        _check_static_assets()
        store = DashboardStore(product=product, geometry=geometry, gate_report=gate_report)
        _serve(store, host=host, port=port)
    except (DashboardError, ContractViolation) as exc:
        typer.echo(f"dashboard failed closed: {exc}", err=True)
        raise typer.Exit(code=1) from exc


if __name__ == "__main__":
    app()
